BEGIN;

-- Delete any existing 2021 survey response for Andy Lower
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'andylower@adapcapital.com');

-- Insert complete 2021 survey response for Andy Lower
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'ADAP Capital LLC',
  'Andy Lower',
  'Founder',
  ARRAY['US/Europe'],
  ARRAY['Asia - South Asia', 'Africa - West Africa', 'Africa - East Africa', 'Africa - Southern Africa', 'Latin America'],
  'Second fund/vehicle',
  'Legal entity, 1st close (or equivalent), First investment',
  'As of March 2020',
  'As of December 2020',
  'As of March 2020',
  'As of December 2020',
  '',
  ARRAY['Open-ended vehicle / Limited liability company or equivalent'],
  'Current',
  'Target',
  '6-7 years',
  ARRAY['High-Growth Ventures (disruptive business models targeting large markets with high growth potential)'],
  ARRAY['Start-up / pre-seed (pre-revenue, concept and business plan development)', 'Early stage / seed (early revenue, product/service development, funds needed to expand business model)'],
  ARRAY['Small ticket tangible assets (e.g. computers, routers, mobile and connectivity systems, office equipment, etc.)', 'Major capital investments (facilities, production equipment, fleet/logistics, etc.)'],
  ARRAY['High Net Worth Individuals (HNWIs)', 'Angel network'],
  'Targeted',
  'Achieved in most recent reporting period',
  'Balanced impact/financial return, Impact first investing (impact outcomes intentionally)',
  ARRAY['Gender', 'Climate / green ventures'],
  true,
  'First',
  'Second',
  'Second',
  ARRAY['Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration']::text[],
  ARRAY['Women representation on the board/investment committee is ≥ 50', 'Provide specific reporting on gender related indicators for your investors/funders', 'Require specific reporting on gender related indicators by your investees/borrowers']::text[],
  ARRAY[]::text[],
  'Your investment amount',
  'Total raise by portfolio company',
  ARRAY['Convertible notes', 'SAFEs'],
  ARRAY['Sector agnostic'],
  '2-3',
  '< or = 2',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 1,
    'Fundraising including access to working capital resources', 1,
    'Strategic / organizational planning', 1,
    'Product/services proof of concept /market share / competitor positioning', 1,
    'Human capital management – hiring/retention/training', 1,
    'Technology (CRM, MIS, telecommunications, etc)', 1,
    'Legal / regulatory', 1,
    'Operations/ production / facilities and infrastructure', 1,
    'Management training', 1,
    'Other', 1
  ),
  ARRAY['Financial investor take-out'],
  '1-4',
  jsonb_build_object(
    'Fundraising with access to global LPs', 1,
    'Fundraising with access to local LPs', 4,
    'Fundraising with access to warehousing capital', 3,
    'Fundraising with access to grant capital for vehicle OPEX', 3,
    'Fundraising with access to TA support', 3,
    'Fund economics', 3,
    'Fund structuring', 3,
    'Investment process (eg origination, due diligence, structuring, closing)', 2,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 2,
    'Fund staff/Human capital management and development', 2,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 2,
    'Exit/monetization opportunities', 1,
    'Legal/regulatory support', 3,
    'Application of impact metrics', 5,
    'Other', 3
  ),
  'Significant negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - high impact',
    'Customer demand', 'To date - high impact',
    'Ability to pay staff salaries', 'To date - high impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - high impact',
    'Ability to pay existing business loans', 'To date - high impact, Anticipate future impact',
    'Access to supply inputs / raw materials', 'To date - high impact, Anticipate future impact',
    'Ability to pay for raw inputs / raw materials', 'To date - high impact',
    'Need to pivot business model', 'To date - high impact'
  ),
  ARRAY['No'],
  ARRAY['New pipeline investments through existing vehicle'],
  ARRAY['Build new partnerships for joint co-investment opportunities, expand pipeline opportunities'],
  '3',
  jsonb_build_object(
    'Fund Economics', 'N/A',
    'LP Profiles', 'N/A',
    'Market Data', 'N/A',
    'Purpose Definition', 'N/A',
    'Access to Capital (DfID proposal)', 'N/A'
  ),
  'It all depends on where you want the network to go and evolve. With 22 deals completed and capital to deploy into an additional 5 deals, we are at a very different stage to most other funds in the network. I''m disappointed that despite our proactive approach as well as our inclusive sector and geographical scope we have had minimal collaboration on co-investing with others in the network. Out of respect to my current investor, I need to be mindful of how much time I give pro-bono to help other groups and how much time is spent directly growing the impact of our fund.',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 'N/A',
    'Fundraising (presentations from I&P, Capria & DGGF)', 'N/A',
    'Portfolio Support (presentations from 10-Xe and AMI)', 'N/A',
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 'N/A',
    'Fundraising 2.0 (peer discussion)', 'N/A',
    'Human Capital (peer discussion)', 'N/A',
    'Co-investing workshop with ADAP (peer discussion)', 'N/A',
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 'N/A',
    'Mentoring Pilot Kick-off', 1
  ),
  'Would love to find more options for exits, both for funds rather than individual deals but aware that is not where the vast majority of the network is at.',
  'Email for more detailed updates/WhatsApp for immediate communication',
  jsonb_build_object(
    'Peer connections and peer learning', 3,
    'Advocacy for early stage investing ', 3,
    'Raised profile/visibility (individual or collective)', 3,
    'Systems change to drive more capital towards local capital providers', 3
  ),
  true,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 3,
    'TA facility to support early fund economics and activities', 3,
    'Advocacy for the early-stage investing ecosystem', 1,
    'Mentoring program (expert led)', 2,
    'Mentoring program (peer-led)', 2,
    'Webinars with peer-to-peer feedback sessions', 2,
    'Webinars with expert-led feedback sessions', 2,
    'Fundraising Readiness Advisory Program for fund managers', 2,
    'Investment readiness for portfolio companies', 2,
    'Fund Manager Portal (ie library of resources, templates etc)', 2,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 1,
    'Joint back office between actively investing fund managers', 2
  ),
  'Not sure',
  ARRAY['Yes, gender lens investing']::text[],
  '',
  '2021-02-08 22:03:51'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'andylower@adapcapital.com';

COMMIT;
