BEGIN;

-- Delete any existing 2021 survey response for Cathy Goddard
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'cathy@fyrefem.com');

-- Insert complete 2021 survey response for Cathy Goddard
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'FyreFem Fund Managers',
  'Cathy Goddard',
  'CEO',
  ARRAY['Africa - Southern Africa'],
  ARRAY['South Africa only'],
  'Open ended - fundraising and heading towards equivalent of 1st close (i.e. lack sufficient committed funds to cover fund economics), Doing deals on a deal-by-deal basis',
  'Legal entity',
  'Not yet achieved',
  'As of March 2020',
  'As of March 2020',
  'As of December 2020',
  NULL,
  ARRAY['Open-ended vehicle / Limited liability company or equivalent'],
  'Current',
  'Target',
  '6-7 years',
  ARRAY['Dynamic Enterprises (proven business models operating in established industries with moderate growth potential)', 'Distressed businesses also = we have a Fix and Build strategy'],
  ARRAY['Growth (established business in need of funds for expansion, assets, working capital etc)', 'Distressed businesses also'],
  ARRAY['Major capital investments (facilities, production equipment, fleet/logistics, etc.)', 'Enterprise growth capital (e.g. intangible investments such as staff build-out, expanded sales & marketing capabilities, new markets, operational and support systems, etc.)', 'Inventory and working capital requirements', 'Bolt on acquisitions'],
  ARRAY['Fund partners', 'Local pension funds', 'High Net Worth Individuals (HNWIs)', 'Development Finance Institutions (DFIs)', 'Impact investing family offices', 'Donors/philanthropy'],
  'Achieved in most recent reporting period',
  'Targeted',
  'Impact investing (positive screening)',
  ARRAY['Gender', 'Job creation'],
  true,
  'First',
  'No Poverty',
  'Gender Equality',
  ARRAY['First'],
  ARRAY['Women ownership/participation interest is ≥ 50%', 'Women representation on the board/investment committee is ≥ 50', 'Female staffing is ≥ 50%', '51% Black women owned'],
  ARRAY[]::text[],
  'Your investment amount, Total raise by portfolio company',
  'Total raise by portfolio company, Total raise by portfolio company',
  ARRAY['Common equity', 'Preferred equity (e.g. certain rights above those available to common equity holders)', 'Senior debt', 'Mezzanine debt'],
  ARRAY['Agriculture / Food supply chain', 'Financial Inclusion / Insurance / Fintech', 'Healthcare', 'Manufacturing', 'Technology / ICT / Telecommunications', 'General services'],
  '2-3',
  '< or = 2',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 3,
    'Fundraising including access to working capital resources', 1,
    'Strategic / organizational planning', 1,
    'Product/services proof of concept /market share / competitor positioning', 5,
    'Human capital management – hiring/retention/training', 3,
    'Technology (CRM, MIS, telecommunications, etc)', 4,
    'Legal / regulatory', 3,
    'Operations/ production / facilities and infrastructure', 5,
    'Management training', 4,
    'Other', 3
  ),
  ARRAY['Interest income/shared revenues and principal repayment', 'Dividends', 'Strategic sale/merger of company', 'These are planned exits. None yet'],
  '0',
  jsonb_build_object(
    'Fundraising with access to global LPs', 1,
    'Fundraising with access to local LPs', 1,
    'Fundraising with access to warehousing capital', 2,
    'Fundraising with access to grant capital for vehicle OPEX', 3,
    'Fundraising with access to TA support', 2,
    'Fund economics', 1,
    'Fund structuring', 1,
    'Investment process (eg origination, due diligence, structuring, closing)', 2,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 4,
    'Fund staff/Human capital management and development', 5,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 3,
    'Exit/monetization opportunities', 2,
    'Legal/regulatory support', 1,
    'Application of impact metrics', 1,
    'Other', 3
  ),
  'Somewhat positive impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - high impact',
    'Ability to pay staff salaries', 'To date - no impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - no impact',
    'Ability to pay existing business loans', 'To date - no impact',
    'Access to supply inputs / raw materials', 'To date - no impact',
    'Ability to pay for raw inputs / raw materials', 'To date - no impact',
    'Need to pivot business model', 'To date - no impact'
  ),
  ARRAY['No'],
  ARRAY['New pipeline investments through existing vehicle', 'New pipeline investments through new vehicle', 'Technical assistance to support portfolio enterprises'],
  ARRAY['Seek increased access to new LP funds internationally', 'Continue dealmaking with another 2 in 2021'],
  '2',
  jsonb_build_object(
    'Fund Economics', 'N/A',
    'LP Profiles', 1,
    'Market Data', 'N/A',
    'Purpose Definition', 1,
    'Access to Capital (DfID proposal)', 1
  ),
  'Hands on workshops on using free resources eg  Impact toolkits eg IRIS+ or FMO ESG toolkit (launched today)',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 1,
    'COVID-19 Response (peer discussion)', 'N/A',
    'Fundraising (presentations from I&P, Capria & DGGF)', 1,
    'Portfolio Support (presentations from 10-Xe and AMI)', 5,
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 1,
    'Fundraising 2.0 (peer discussion)', 1,
    'Human Capital (peer discussion)', 'N/A',
    'Co-investing workshop with ADAP (peer discussion)', 'N/A',
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 'N/A',
    'Mentoring Pilot Kick-off', 'N/A'
  ),
  'Worry about time needed to participate meaningful in a working group. Multiple demands from other collaborations eg GenderSmart and WAI Group Emerging Managers.',
  'WhatsApp only',
  jsonb_build_object(
    'Peer connections and peer learning', 1,
    'Advocacy for early stage investing ', 1,
    'Raised profile/visibility (individual or collective)', 1,
    'Systems change to drive more capital towards local capital providers', 1
  ),
  true,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 1,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 2,
    'Mentoring program (expert led)', 1,
    'Mentoring program (peer-led)', 1,
    'Webinars with peer-to-peer feedback sessions', 3,
    'Webinars with expert-led feedback sessions', 2,
    'Fundraising Readiness Advisory Program for fund managers', 1,
    'Investment readiness for portfolio companies', 1,
    'Fund Manager Portal (ie library of resources, templates etc)', 1,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 3,
    'Joint back office between actively investing fund managers', 1
  ),
  'Not sure',
  ARRAY['No'],
  'Thanks for all the hard work',
  '2021-01-26 13:15:56'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'cathy@fyrefem.com';

COMMIT;
