BEGIN;

-- Delete any existing 2021 survey response for Chai Musoni
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'chai@vakayi.com');

-- Insert complete 2021 survey response for Chai Musoni
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Vakayi Capital',
  'Chai Musoni',
  'CEO/Partner',
  ARRAY['Africa - Southern Africa'],
  ARRAY['Africa - Southern Africa'],
  'Closed ended - fundraising',
  '1st close (or equivalent)',
  'Not yet achieved',
  'As of December 2020',
  'Legal entity, First investment',
  'As of December 2020',
  'Closed-end fund',
  ARRAY['Mezzanine debt', 'Shared revenue/earnings instruments'],
  'Current',
  'Target',
  '4-5 years',
  ARRAY['Dynamic Enterprises (proven business models operating in established industries with moderate growth potential)'],
  ARRAY['Growth (established business in need of funds for expansion, assets, working capital etc)'],
  ARRAY['Major capital investments (facilities, production equipment, fleet/logistics, etc.)', 'Inventory and working capital requirements'],
  ARRAY['Local pension funds', 'High Net Worth Individuals (HNWIs)', 'Development Finance Institutions (DFIs)', 'Impact investing family offices'],
  'Achieved in most recent reporting period',
  'Targeted',
  'Financial return first',
  ARRAY['Gender', 'Youth', 'Job creation'],
  true,
  'First',
  'First',
  'First',
  ARRAY['Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration'],
  ARRAY['Provide specific reporting on gender related indicators for your investors/funders'],
  ARRAY[]::text[],
  'Your investment amount, Total raise by portfolio company',
  'Total raise by portfolio company',
  ARRAY['Mezzanine debt', 'Shared revenue/earnings instruments'],
  ARRAY['Sector agnostic'],
  '2-3',
  '3-5',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 1,
    'Fundraising including access to working capital resources', 1,
    'Strategic / organizational planning', 2,
    'Product/services proof of concept /market share / competitor positioning', 4,
    'Human capital management – hiring/retention/training', 3,
    'Technology (CRM, MIS, telecommunications, etc)', 3,
    'Legal / regulatory', 4,
    'Operations/ production / facilities and infrastructure', 3,
    'Management training', 3,
    'Other', 5
  ),
  ARRAY['Interest income/shared revenues and principal repayment'],
  '0',
  jsonb_build_object(
    'Fundraising with access to global LPs', 1,
    'Fundraising with access to local LPs', 2,
    'Fundraising with access to warehousing capital', 5,
    'Fundraising with access to grant capital for vehicle OPEX', 3,
    'Fundraising with access to TA support', 1,
    'Fund economics', 4,
    'Fund structuring', 3,
    'Investment process (eg origination, due diligence, structuring, closing)', 5,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 4,
    'Fund staff/Human capital management and development', 4,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 3,
    'Exit/monetization opportunities', 5,
    'Legal/regulatory support', 5,
    'Application of impact metrics', 4,
    'Other', 5
  ),
  'Significant negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - no impact',
    'Customer demand', 'To date - slight impact',
    'Ability to pay staff salaries', 'To date - slight impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - slight impact',
    'Ability to pay existing business loans', 'To date - high impact',
    'Access to supply inputs / raw materials', 'To date - slight impact',
    'Ability to pay for raw inputs / raw materials', 'To date - high impact',
    'Need to pivot business model', 'To date - no impact'
  ),
  ARRAY['No'],
  ARRAY['Growth capital for existing portfolio to increase market share', 'New pipeline investments through existing vehicle'],
  ARRAY['Seek increased access to new LP funds locally', 'Seek increased access to new LP funds internationally'],
  '3',
  jsonb_build_object(
    'Fund Economics', 3,
    'LP Profiles', 3,
    'Market Data', 4,
    'Purpose Definition', 3,
    'Access to Capital (DfID proposal)', 3
  ),
  'no',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 3,
    'COVID-19 Response (peer discussion)', 2,
    'Fundraising (presentations from I&P, Capria & DGGF)', 3,
    'Portfolio Support (presentations from 10-Xe and AMI)', 3,
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 2,
    'Fundraising 2.0 (peer discussion)', 2,
    'Human Capital (peer discussion)', 3,
    'Co-investing workshop with ADAP (peer discussion)', 3,
    'Fundraising 3.0 – local capital (peer discussion)', 2,
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 3,
    'Mentoring Pilot Kick-off', 2
  ),
  'No',
  'Both Slack (eg for working groups etc) and WhatsApp (eg for more time sensitive communications)',
  jsonb_build_object(
    'Peer connections and peer learning', 2,
    'Advocacy for early stage investing ', 2,
    'Raised profile/visibility (individual or collective)', 3,
    'Systems change to drive more capital towards local capital providers', 2
  ),
  false,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 3,
    'TA facility to support early fund economics and activities', 2,
    'Advocacy for the early-stage investing ecosystem', 1,
    'Mentoring program (expert led)', 3,
    'Mentoring program (peer-led)', 2,
    'Webinars with peer-to-peer feedback sessions', 1,
    'Webinars with expert-led feedback sessions', 2,
    'Fundraising Readiness Advisory Program for fund managers', 2,
    'Investment readiness for portfolio companies', 2,
    'Fund Manager Portal (ie library of resources, templates etc)', 1,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 1,
    'Joint back office between actively investing fund managers', 1
  ),
  'Yes, as a mentee',
  ARRAY['No'],
  'Capital raising needs to receive much more attention. Without ultimately securing capital everything else becomes redudant.',
  '2021-01-29 09:16:17'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'chai@vakayi.com';

COMMIT;
