BEGIN;

-- Delete any existing 2021 survey response for Dayo Koleowo
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'dayo@microtraction.com');

-- Insert complete 2021 survey response for Dayo Koleowo
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Microtraction',
  'Dayo Koleowo',
  'Partner',
  ARRAY['Africa - West Africa'],
  ARRAY['Pan-African'],
  'Open-ended - achieved equivalent of 1st close with sufficient committed funds to cover fund economics, Second fund/vehicle',
  'Legal entity, 1st close (or equivalent), First investment',
  '1st close (or equivalent)',
  'First investment',
  'As of March 2020',
  'As of December 2020',
  '',
  ARRAY['Open-ended vehicle / Limited liability company or equivalent'],
  'Current',
  'Target',
  '8+ years',
  ARRAY['High-Growth Ventures (disruptive business models targeting large markets with high growth potential)'],
  ARRAY['Early stage / seed (early revenue, product/service development, funds needed to expand business model)'],
  ARRAY['Venture launch – invest in initial staff, product/services development and market acceptance', 'Small ticket tangible assets (e.g. computers, routers, mobile and connectivity systems, office equipment, etc.)'],
  ARRAY['High Net Worth Individuals (HNWIs)', 'Angel network', 'Development Finance Institutions (DFIs)'],
  'Not yet achieved',
  'Targeted',
  'Financial return first, Balanced impact/financial return',
  ARRAY['N/A'],
  false,
  NULL,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['Female staffing is ≥ 50%', 'Provide specific reporting on gender related indicators for your investors/funders'],
  'Your investment amount, Total raise by portfolio company',
  'Total raise by portfolio company',
  ARRAY['Preferred equity (e.g. certain rights above those available to common equity holders)', 'SAFEs'],
  ARRAY['Sector agnostic'],
  '2-3',
  '3-5',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 4,
    'Fundraising including access to working capital resources', 3,
    'Strategic / organizational planning', 5,
    'Product/services proof of concept /market share / competitor positioning', 4,
    'Human capital management – hiring/retention/training', 5,
    'Technology (CRM, MIS, telecommunications, etc)', 3,
    'Legal / regulatory', 5,
    'Operations/ production / facilities and infrastructure', 4,
    'Management training', 3,
    'Other', 5
  ),
  ARRAY['Strategic sale/merger of company'],
  '0',
  jsonb_build_object(
    'Fundraising with access to global LPs', 2,
    'Fundraising with access to local LPs', 2,
    'Fundraising with access to warehousing capital', 5,
    'Fundraising with access to grant capital for vehicle OPEX', 3,
    'Fundraising with access to TA support', 2,
    'Fund economics', 2,
    'Fund structuring', 3,
    'Investment process (eg origination, due diligence, structuring, closing)', 3,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 3,
    'Fund staff/Human capital management and development', 3,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 3,
    'Exit/monetization opportunities', 3,
    'Legal/regulatory support', 2,
    'Application of impact metrics', 4,
    'Other', 5
  ),
  'Somewhat positive impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - slight impact',
    'Ability to pay staff salaries', 'To date - slight impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - slight impact',
    'Ability to pay existing business loans', 'To date - no impact',
    'Access to supply inputs / raw materials', 'To date - no impact',
    'Ability to pay for raw inputs / raw materials', 'To date - no impact',
    'Need to pivot business model', 'To date - slight impact'
  ),
  ARRAY['No'],
  ARRAY['New pipeline investments through new vehicle'],
  ARRAY['Seek increased access to new LP funds locally', 'Increase use of technology in order to lower fund operational costs', 'Build new partnerships for joint co-investment opportunities, expand pipeline opportunities'],
  '2',
  jsonb_build_object(
    'Fund Economics', 'N/A',
    'LP Profiles', 'N/A',
    'Market Data', 'N/A',
    'Purpose Definition', 'N/A',
    'Access to Capital (DfID proposal)', 'N/A'
  ),
  'N/A',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 'N/A',
    'Fundraising (presentations from I&P, Capria & DGGF)', 'N/A',
    'Portfolio Support (presentations from 10-Xe and AMI)', 'N/A',
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 'N/A',
    'Fundraising 2.0 (peer discussion)', 'N/A',
    'Human Capital (peer discussion)', 'N/A',
    'Co-investing workshop with ADAP (peer discussion)', 'N/A',
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 'N/A',
    'Mentoring Pilot Kick-off', 2
  ),
  'N/A',
  'Both Slack (eg for working groups etc) and WhatsApp (eg for more time sensitive communications)',
  jsonb_build_object(
    'Peer connections and peer learning', 2,
    'Advocacy for early stage investing ', 'N/A',
    'Raised profile/visibility (individual or collective)', 3,
    'Systems change to drive more capital towards local capital providers', 'N/A'
  ),
  false,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 3,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 2,
    'Mentoring program (expert led)', 2,
    'Mentoring program (peer-led)', 2,
    'Webinars with peer-to-peer feedback sessions', 1,
    'Webinars with expert-led feedback sessions', 1,
    'Fundraising Readiness Advisory Program for fund managers', 2,
    'Investment readiness for portfolio companies', 1,
    'Fund Manager Portal (ie library of resources, templates etc)', 1,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 2,
    'Joint back office between actively investing fund managers', 2
  ),
  'Not sure',
  ARRAY['No'],
  '',
  '2021-02-02 07:40:45'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'dayo@microtraction.com';

COMMIT;
