BEGIN;

-- Delete any existing 2021 survey response for Jaap-Jan Verboom
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'jaap-jan@truvalu-group.com');

-- Insert complete 2021 survey response for Jaap-Jan Verboom
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Truvalu',
  'Jaap-Jan Verboom',
  'Founder/ Director',
  ARRAY['US/Europe', 'Asia - South Asia', 'Africa - East Africa', 'Latin America'],
  ARRAY['Asia - South Asia', 'Africa - East Africa', 'Latin America'],
  'Open-ended - achieved equivalent of 1st close with sufficient committed funds to cover fund economics',
  '1st close (or equivalent)',
  'Not yet achieved',
  'As of March 2020',
  'Legal entity',
  'First investment',
  'Open-ended vehicle / Limited liability company or equivalent',
  ARRAY['Common equity', 'Convertible notes', 'Mezzanine debt'],
  'Current',
  'Target',
  '8+ years',
  ARRAY['Dynamic Enterprises (proven business models operating in established industries with moderate growth potential)', 'Niche Ventures (innovative products/services targeting niche markets with growth ambitions)'],
  ARRAY['Early stage / seed (early revenue, product/service development, funds needed to expand business model)', 'Growth (established business in need of funds for expansion, assets, working capital etc)'],
  ARRAY['Major capital investments (facilities, production equipment, fleet/logistics, etc.)', 'Inventory and working capital requirements'],
  ARRAY['Fund partners', 'High Net Worth Individuals (HNWIs)', 'Crowd funding'],
  'Achieved in most recent reporting period',
  'Targeted',
  'Balanced impact/financial return',
  ARRAY['N/A'],
  true,
  'First',
  'Second',
  'Third',
  ARRAY['Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration'],
  ARRAY['Provide specific reporting on gender related indicators for your investors/funders', 'Require specific reporting on gender related indicators by your investees/borrowers'],
  ARRAY[]::text[],
  'Your investment amount, Total raise by portfolio company',
  'Your investment amount, Total raise by portfolio company',
  ARRAY['Common equity', 'Convertible notes', 'Mezzanine debt'],
  ARRAY['Agriculture / Food supply chain'],
  '0',
  '10+',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 1,
    'Fundraising including access to working capital resources', 2,
    'Strategic / organizational planning', 2,
    'Product/services proof of concept /market share / competitor positioning', 4,
    'Human capital management – hiring/retention/training', 2,
    'Technology (CRM, MIS, telecommunications, etc)', 5,
    'Legal / regulatory', 3,
    'Operations/ production / facilities and infrastructure', 2,
    'Management training', 1,
    'Other', 3
  ),
  ARRAY['Interest income/shared revenues and principal repayment', 'Dividends', 'Management buyout'],
  '1-4',
  jsonb_build_object(
    'Fundraising with access to global LPs', 1,
    'Fundraising with access to local LPs', 1,
    'Fundraising with access to warehousing capital', 3,
    'Fundraising with access to grant capital for vehicle OPEX', 5,
    'Fundraising with access to TA support', 1,
    'Fund economics', 3,
    'Fund structuring', 5,
    'Investment process (eg origination, due diligence, structuring, closing)', 4,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 3,
    'Fund staff/Human capital management and development', 1,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 4,
    'Exit/monetization opportunities', 1,
    'Legal/regulatory support', 2,
    'Application of impact metrics', 3,
    'Other', 3
  ),
  'Significant negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - high impact, Anticipate future impact',
    'Customer demand', 'To date - high impact, Anticipate future impact',
    'Ability to pay staff salaries', 'To date - high impact, Anticipate future impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - high impact, Anticipate future impact',
    'Ability to pay existing business loans', 'To date - high impact, Anticipate future impact',
    'Access to supply inputs / raw materials', 'To date - high impact, Anticipate future impact',
    'Ability to pay for raw inputs / raw materials', 'To date - high impact, Anticipate future impact',
    'Need to pivot business model', 'To date - slight impact, Anticipate no future impact'
  ),
  ARRAY['Yes, government support (financial)', 'Yes, non-financial assistance'],
  ARRAY['Growth capital for existing portfolio to increase market share', 'Growth capital for existing portfolio to enter new markets/expand business line(s)', 'New pipeline investments through existing vehicle'],
  ARRAY['Seek increased access to new LP funds locally', 'Seek increased access to new LP funds internationally', 'Build new partnerships for joint co-investment opportunities, expand pipeline opportunities'],
  '3',
  jsonb_build_object(
    'Fund Economics', 'N/A',
    'LP Profiles', 'N/A',
    'Market Data', 'N/A',
    'Purpose Definition', 'N/A',
    'Access to Capital (DfID proposal)', 'N/A'
  ),
  'n/a',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 2,
    'Fundraising (presentations from I&P, Capria & DGGF)', 1,
    'Portfolio Support (presentations from 10-Xe and AMI)', 5,
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 5,
    'Fundraising 2.0 (peer discussion)', 2,
    'Human Capital (peer discussion)', 'N/A',
    'Co-investing workshop with ADAP (peer discussion)', 2,
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 5,
    'Mentoring Pilot Kick-off', 'N/A'
  ),
  'I don''t know :-(',
  'Both Slack (eg for working groups etc) and WhatsApp (eg for more time sensitive communications)',
  jsonb_build_object(
    'Peer connections and peer learning', 2,
    'Advocacy for early stage investing ', 3,
    'Raised profile/visibility (individual or collective)', 3,
    'Systems change to drive more capital towards local capital providers', 2
  ),
  true,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 3,
    'TA facility to support early fund economics and activities', 2,
    'Advocacy for the early-stage investing ecosystem', 2,
    'Mentoring program (expert led)', 2,
    'Mentoring program (peer-led)', 3,
    'Webinars with peer-to-peer feedback sessions', 2,
    'Webinars with expert-led feedback sessions', 1,
    'Fundraising Readiness Advisory Program for fund managers', 1,
    'Investment readiness for portfolio companies', 2,
    'Fund Manager Portal (ie library of resources, templates etc)', 2,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 2,
    'Joint back office between actively investing fund managers', 3
  ),
  'No',
  ARRAY['Yes, open ended vehicles'],
  NULL,
  '2021-01-29 16:40:07'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'jaap-jan@truvalu-group.com';

COMMIT;
