BEGIN;

-- Delete any existing 2021 survey response for Jason Musyoka
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'jason@viktoria.co.ke');

-- Insert complete 2021 survey response for Jason Musyoka
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'ViKtoria Business Angels Network',
  'Jason Musyoka',
  'Manager',
  ARRAY['Africa - East Africa'],
  ARRAY['Africa - East Africa'],
  'Open ended - fundraising and heading towards equivalent of 1st close (i.e. lack sufficient committed funds to cover fund economics)',
  'Legal entity, 1st close (or equivalent), First investment',
  '1st close (or equivalent)',
  'First investment',
  'No investments as of March 2020',
  'As of December 2020',
  '',
  ARRAY['Angel co-investments', 'Open-ended vehicle / Limited liability company or equivalent'],
  'Current',
  'Target',
  '4-5 years',
  ARRAY['Dynamic Enterprises (proven business models operating in established industries with moderate growth potential)', 'High-Growth Ventures (disruptive business models targeting large markets with high growth potential)'],
  ARRAY['Early stage / seed (early revenue, product/service development, funds needed to expand business model)'],
  ARRAY['Venture launch – invest in initial staff, product/services development and market acceptance', 'Inventory and working capital requirements'],
  ARRAY['High Net Worth Individuals (HNWIs)', 'Development Finance Institutions (DFIs)'],
  'Targeted',
  'Targeted',
  'Financial return first',
  ARRAY['N/A'],
  false,
  NULL,
  NULL,
  NULL,
  ARRAY['Investment Consideration'],
  ARRAY[]::text[],
  ARRAY['None'],
  'Your investment amount',
  'Total raise by portfolio company',
  ARRAY['Convertible notes', 'SAFEs'],
  ARRAY['Sector agnostic'],
  '0',
  '< or = 2',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 3,
    'Fundraising including access to working capital resources', 2,
    'Strategic / organizational planning', 3,
    'Product/services proof of concept /market share / competitor positioning', 2,
    'Human capital management – hiring/retention/training', 4,
    'Technology (CRM, MIS, telecommunications, etc)', 4,
    'Legal / regulatory', 4,
    'Operations/ production / facilities and infrastructure', 4,
    'Management training', 4,
    'Other', 5
  ),
  ARRAY['Strategic sale/merger of company'],
  '0',
  jsonb_build_object(
    'Fundraising with access to global LPs', 1,
    'Fundraising with access to local LPs', 1,
    'Fundraising with access to warehousing capital', 2,
    'Fundraising with access to grant capital for vehicle OPEX', 2,
    'Fundraising with access to TA support', 2,
    'Fund economics', 4,
    'Fund structuring', 4,
    'Investment process (eg origination, due diligence, structuring, closing)', 3,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 3,
    'Fund staff/Human capital management and development', 4,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 4,
    'Exit/monetization opportunities', 3,
    'Legal/regulatory support', 4,
    'Application of impact metrics', 4,
    'Other', 5
  ),
  'Somewhat negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - slight impact',
    'Ability to pay staff salaries', 'To date - slight impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - slight impact',
    'Ability to pay existing business loans', 'To date - slight impact',
    'Access to supply inputs / raw materials', 'To date - high impact',
    'Ability to pay for raw inputs / raw materials', 'To date - high impact',
    'Need to pivot business model', 'To date - slight impact'
  ),
  ARRAY['No'],
  ARRAY['New pipeline investments through new vehicle'],
  ARRAY['Seek increased access to new LP funds internationally', 'Increase application of alternative debt instruments (e.g. mezzanine debt, convertible debt, or shared revenue instruments)', 'Build new partnerships for joint co-investment opportunities, expand pipeline opportunities'],
  '4',
  jsonb_build_object(
    'Fund Economics', 5,
    'LP Profiles', 5,
    'Market Data', 4,
    'Purpose Definition', 4,
    'Access to Capital (DfID proposal)', 5
  ),
  'Not at the moment',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 3,
    'COVID-19 Response (peer discussion)', 3,
    'Fundraising (presentations from I&P, Capria & DGGF)', 4,
    'Portfolio Support (presentations from 10-Xe and AMI)', 3,
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 4,
    'Fundraising 2.0 (peer discussion)', 4,
    'Human Capital (peer discussion)', 3,
    'Co-investing workshop with ADAP (peer discussion)', 3,
    'Fundraising 3.0 – local capital (peer discussion)', 4,
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 3,
    'Mentoring Pilot Kick-off', 'N/A'
  ),
  'Not at the moment',
  'WhatsApp only',
  jsonb_build_object(
    'Peer connections and peer learning', 5,
    'Advocacy for early stage investing ', 5,
    'Raised profile/visibility (individual or collective)', 3,
    'Systems change to drive more capital towards local capital providers', 3
  ),
  false,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 3,
    'TA facility to support early fund economics and activities', 3,
    'Advocacy for the early-stage investing ecosystem', 2,
    'Mentoring program (expert led)', 2,
    'Mentoring program (peer-led)', 2,
    'Webinars with peer-to-peer feedback sessions', 2,
    'Webinars with expert-led feedback sessions', 3,
    'Fundraising Readiness Advisory Program for fund managers', 2,
    'Investment readiness for portfolio companies', 3,
    'Fund Manager Portal (ie library of resources, templates etc)', 2,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 2,
    'Joint back office between actively investing fund managers', 1
  ),
  'Yes, as a mentee',
  ARRAY['No'],
  'Found the sessions very valuable',
  '2021-02-01 14:19:01'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'jason@viktoria.co.ke';

COMMIT;
