BEGIN;

-- Delete any existing 2021 survey response for Jenny Ahlzen
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'jenny@amamventures.com');

-- Insert complete 2021 survey response for Jenny Ahlzen
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Amam Ventures',
  'Jenny Ahlzen',
  'Co-founder and managing partner',
  ARRAY['Middle East'],
  ARRAY['Middle East'],
  'currently in pilot phase, creating a track record and working towards a first close',
  'Legal entity',
  'Not yet achieved',
  'As of December 2020',
  NULL,
  'As of December 2020',
  'pilot signed in Dec 2020 and literally now in the process of making our first few investments',
  ARRAY['Open-ended vehicle / Limited liability company or equivalent'],
  'Current',
  'Target',
  '4-5 years',
  ARRAY['Livelihood Sustaining Enterprises (formal/informal family run businesses targeting incremental growth)', 'Dynamic Enterprises (proven business models operating in established industries with moderate growth potential)'],
  ARRAY['Growth (established business in need of funds for expansion, assets, working capital etc)'],
  ARRAY['Major capital investments (facilities, production equipment, fleet/logistics, etc.)', 'Enterprise growth capital (e.g. intangible investments such as staff build-out, expanded sales & marketing capabilities, new markets, operational and support systems, etc.)', 'Inventory and working capital requirements'],
  ARRAY['High Net Worth Individuals (HNWIs)', 'Development Finance Institutions (DFIs)', 'Impact investing family offices', 'Corporates'],
  '',
  'Targeted',
  'Balanced impact/financial return',
  ARRAY['Gender', 'Job creation'],
  true,
  'First',
  'Second',
  'Third',
  ARRAY['Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration'],
  ARRAY['Women ownership/participation interest is ≥ 50%', 'Women representation on the board/investment committee is ≥ 50', 'Female staffing is ≥ 50%', 'Provide specific reporting on gender related indicators for your investors/funders', 'Require specific reporting on gender related indicators by your investees/borrowers'],
  ARRAY[]::text[],
  'Your investment amount',
  'Your investment amount',
  ARRAY['Mezzanine debt', 'Shared revenue/earnings instruments'],
  ARRAY['Sector agnostic'],
  '2-3',
  '3-5',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 1,
    'Fundraising including access to working capital resources', 3,
    'Strategic / organizational planning', 2,
    'Product/services proof of concept /market share / competitor positioning', 3,
    'Human capital management – hiring/retention/training', 2,
    'Technology (CRM, MIS, telecommunications, etc)', 4,
    'Legal / regulatory', 3,
    'Operations/ production / facilities and infrastructure', 3,
    'Management training', 1,
    'Other', 5
  ),
  ARRAY['Interest income/shared revenues and principal repayment', 'Other types of self-liquidating repayment structures'],
  '0',
  jsonb_build_object(
    'Fundraising with access to global LPs', 1,
    'Fundraising with access to local LPs', 5,
    'Fundraising with access to warehousing capital', 5,
    'Fundraising with access to grant capital for vehicle OPEX', 2,
    'Fundraising with access to TA support', 1,
    'Fund economics', 2,
    'Fund structuring', 2,
    'Investment process (eg origination, due diligence, structuring, closing)', 4,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 2,
    'Fund staff/Human capital management and development', 4,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 3,
    'Exit/monetization opportunities', 5,
    'Legal/regulatory support', 4,
    'Application of impact metrics', 1,
    'Other', 5
  ),
  'Somewhat positive impact',
  jsonb_build_object(
    'Staff attendance', 'To date - no impact',
    'Customer demand', 'To date - high impact',
    'Ability to pay staff salaries', 'To date - slight impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - slight impact',
    'Ability to pay existing business loans', 'To date - slight impact',
    'Access to supply inputs / raw materials', 'To date - high impact',
    'Ability to pay for raw inputs / raw materials', 'To date - slight impact',
    'Need to pivot business model', 'To date - slight impact'
  ),
  ARRAY['No'],
  ARRAY['New pipeline investments through new vehicle', 'Technical assistance to support portfolio enterprises'],
  ARRAY['Increase application of alternative debt instruments (e.g. mezzanine debt, convertible debt, or shared revenue instruments)', 'Increase use of technology in order to lower fund operational costs', 'Increase use of data and technology to facilitate investment decisions'],
  '1',
  jsonb_build_object(
    'Fund Economics', 'N/A',
    'LP Profiles', 'N/A',
    'Market Data', 'N/A',
    'Purpose Definition', 'N/A',
    'Access to Capital (DfID proposal)', 'N/A'
  ),
  'I''m a relatively new member so this will be my first event',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 'N/A',
    'Fundraising (presentations from I&P, Capria & DGGF)', 'N/A',
    'Portfolio Support (presentations from 10-Xe and AMI)', 'N/A',
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 'N/A',
    'Fundraising 2.0 (peer discussion)', 'N/A',
    'Human Capital (peer discussion)', 'N/A',
    'Co-investing workshop with ADAP (peer discussion)', 'N/A',
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 'N/A',
    'Mentoring Pilot Kick-off', 'N/A'
  ),
  'you have done so many already! If possible, would really like to get access to previous webinars',
  'WhatsApp only',
  jsonb_build_object(
    'Peer connections and peer learning', 'N/A',
    'Advocacy for early stage investing ', 'N/A',
    'Raised profile/visibility (individual or collective)', 'N/A',
    'Systems change to drive more capital towards local capital providers', 'N/A'
  ),
  false,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 2,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 3,
    'Mentoring program (expert led)', 1,
    'Mentoring program (peer-led)', 1,
    'Webinars with peer-to-peer feedback sessions', 2,
    'Webinars with expert-led feedback sessions', 2,
    'Fundraising Readiness Advisory Program for fund managers', 1,
    'Investment readiness for portfolio companies', 2,
    'Fund Manager Portal (ie library of resources, templates etc)', 2,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 2,
    'Joint back office between actively investing fund managers', 1
  ),
  'Yes, as a mentor, Yes, as a mentee',
  ARRAY['as mentioned above, this will be my first event with the ESCP, so i think it''d make sense to learn from others first? Happy to present though if you are short on presenters :)'],
  'Looking forward to it!',
  '2021-01-29 19:46:05'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'jenny@amamventures.com';

COMMIT;
