BEGIN;

-- Delete any existing 2021 survey response for Lavanya Anand
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'lavanya@vestedworld.com');

-- Insert complete 2021 survey response for Lavanya Anand
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'VestedWorld',
  'Lavanya Anand',
  'Vice President',
  ARRAY['US/Europe', 'Africa - East Africa'],
  ARRAY['Africa - West Africa', 'Africa - East Africa'],
  'Closed ended - completed second close, Started fundraising for second fund',
  'Legal entity',
  '1st close (or equivalent)',
  '1st close (or equivalent)',
  'As of March 2020',
  'As of December 2020',
  '',
  ARRAY['Closed-end fund'],
  'Current',
  'Target',
  '6-7 years',
  ARRAY['Dynamic Enterprises (proven business models operating in established industries with moderate growth potential)', 'High-Growth Ventures (disruptive business models targeting large markets with high growth potential)'],
  ARRAY['Growth (established business in need of funds for expansion, assets, working capital etc)', 'Pre-Series A / Series A'],
  ARRAY['Major capital investments (facilities, production equipment, fleet/logistics, etc.)', 'Enterprise growth capital (e.g. intangible investments such as staff build-out, expanded sales & marketing capabilities, new markets, operational and support systems, etc.)', 'Inventory and working capital requirements'],
  ARRAY['Local pension funds', 'High Net Worth Individuals (HNWIs)', 'Development Finance Institutions (DFIs)', 'Impact investing family offices', 'Donors/philanthropy'],
  'Achieved in most recent reporting period',
  'Targeted',
  'Financial return first, Responsible/ESG investing (negative screening)',
  ARRAY['Job creation'],
  true,
  'Second',
  'Third',
  'First',
  ARRAY['Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration'],
  ARRAY['At least 1 woman on IC, at least 1 woman partner'],
  ARRAY[]::text[],
  'Your investment amount',
  'Total raise by portfolio company',
  ARRAY['Preferred equity (e.g. certain rights above those available to common equity holders)', 'Convertible notes'],
  ARRAY['Agriculture / Food supply chain', 'Distribution / Logistics', 'Education', 'Financial Inclusion / Insurance / Fintech', 'Fast Moving Consumer Goods (FMCG)', 'Healthcare', 'Manufacturing', 'Technology / ICT / Telecommunications'],
  '4-5',
  '3-5',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 3,
    'Fundraising including access to working capital resources', 1,
    'Strategic / organizational planning', 4,
    'Product/services proof of concept /market share / competitor positioning', 5,
    'Human capital management – hiring/retention/training', 2,
    'Technology (CRM, MIS, telecommunications, etc)', 5,
    'Legal / regulatory', 5,
    'Operations/ production / facilities and infrastructure', 5,
    'Management training', 5,
    'Other', 5
  ),
  ARRAY['Strategic sale/merger of company', 'Financial investor take-out'],
  '0',
  jsonb_build_object(
    'Fundraising with access to global LPs', 1,
    'Fundraising with access to local LPs', 4,
    'Fundraising with access to warehousing capital', 5,
    'Fundraising with access to grant capital for vehicle OPEX', 2,
    'Fundraising with access to TA support', 2,
    'Fund economics', 2,
    'Fund structuring', 5,
    'Investment process (eg origination, due diligence, structuring, closing)', 5,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 5,
    'Fund staff/Human capital management and development', 5,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 5,
    'Exit/monetization opportunities', 1,
    'Legal/regulatory support', 5,
    'Application of impact metrics', 3,
    'Other', 5
  ),
  'Somewhat negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - no impact',
    'Customer demand', 'To date - slight impact',
    'Ability to pay staff salaries', 'To date - slight impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - slight impact',
    'Ability to pay existing business loans', 'To date - high impact',
    'Access to supply inputs / raw materials', 'To date - slight impact',
    'Ability to pay for raw inputs / raw materials', 'To date - no impact',
    'Need to pivot business model', 'To date - slight impact'
  ),
  ARRAY['No'],
  ARRAY['New pipeline investments through new vehicle', 'Technical assistance to support portfolio enterprises'],
  ARRAY['Increase use of technology in order to lower fund operational costs', 'Increase use of data and technology to facilitate investment decisions', 'Build new partnerships for joint co-investment opportunities, expand pipeline opportunities'],
  '2',
  jsonb_build_object(
    'Fund Economics', 1,
    'LP Profiles', 'N/A',
    'Market Data', 'N/A',
    'Purpose Definition', 'N/A',
    'Access to Capital (DfID proposal)', 'N/A'
  ),
  'Shared back-office services, Exit landscape, Fund manager database',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 2,
    'Fundraising (presentations from I&P, Capria & DGGF)', 1,
    'Portfolio Support (presentations from 10-Xe and AMI)', 'N/A',
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 2,
    'Fundraising 2.0 (peer discussion)', 'N/A',
    'Human Capital (peer discussion)', 2,
    'Co-investing workshop with ADAP (peer discussion)', 1,
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 2,
    'Mentoring Pilot Kick-off', 1
  ),
  'Successful exits, technology DD, virtual DD',
  'Both Slack (eg for working groups etc) and WhatsApp (eg for more time sensitive communications)',
  jsonb_build_object(
    'Peer connections and peer learning', 1,
    'Advocacy for early stage investing ', 2,
    'Raised profile/visibility (individual or collective)', 3,
    'Systems change to drive more capital towards local capital providers', 'N/A'
  ),
  false,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 3,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 2,
    'Mentoring program (expert led)', 2,
    'Mentoring program (peer-led)', 2,
    'Webinars with peer-to-peer feedback sessions', 2,
    'Webinars with expert-led feedback sessions', 1,
    'Fundraising Readiness Advisory Program for fund managers', 2,
    'Investment readiness for portfolio companies', 2,
    'Fund Manager Portal (ie library of resources, templates etc)', 1,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 1,
    'Joint back office between actively investing fund managers', 1
  ),
  'Not sure',
  ARRAY['No'],
  '',
  '2021-02-01 10:58:13'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'lavanya@vestedworld.com';

COMMIT;
