BEGIN;

-- Delete any existing 2021 survey response for Lewam Kefela
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'lkefela@gmail.com');

-- Insert complete 2021 survey response for Lewam Kefela
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Village Capital',
  'Lewam Kefela',
  'Investment Director',
  ARRAY['US/Europe', 'Africa - East Africa', 'Latin America'],
  ARRAY['US/Europe', 'Africa - West Africa', 'Africa - East Africa', 'Africa - North Africa', 'Latin America', 'Middle East'],
  'Closed ended - fundraising',
  '',
  '',
  '',
  '',
  '',
  '',
  ARRAY['Closed-end fund'],
  '',
  '',
  '4-5 years',
  ARRAY['High-Growth Ventures (disruptive business models targeting large markets with high growth potential)'],
  ARRAY['Start-up / pre-seed (pre-revenue, concept and business plan development)', 'Early stage / seed (early revenue, product/service development, funds needed to expand business model)'],
  ARRAY['Venture launch – invest in initial staff, product/services development and market acceptance', 'Small ticket tangible assets (e.g. computers, routers, mobile and connectivity systems, office equipment, etc.)', 'Inventory and working capital requirements'],
  ARRAY['Fund partners', 'High Net Worth Individuals (HNWIs)', 'Development Finance Institutions (DFIs)', 'Impact investing family offices', 'Corporates'],
  '',
  '',
  'Financial return first, Impact investing (positive screening)',
  ARRAY['Gender'],
  true,
  'Third',
  'First',
  'Second',
  ARRAY['Investment Consideration', 'Investment Consideration']::text[],
  ARRAY['Provide specific reporting on gender related indicators for your investors/funders']::text[],
  ARRAY[]::text[],
  '',
  '',
  ARRAY['Preferred equity (e.g. certain rights above those available to common equity holders)', 'Convertible notes', 'Shared revenue/earnings instruments', 'SAFEs'],
  ARRAY['Agriculture / Food supply chain', 'Education', 'Energy / Renewables / Green Mobility', 'Financial Inclusion / Insurance / Fintech', 'Healthcare'],
  '1',
  '< or = 2',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 4,
    'Fundraising including access to working capital resources', 5,
    'Strategic / organizational planning', 4,
    'Product/services proof of concept /market share / competitor positioning', 4,
    'Human capital management – hiring/retention/training', 4,
    'Technology (CRM, MIS, telecommunications, etc)', 3,
    'Legal / regulatory', 3,
    'Operations/ production / facilities and infrastructure', 3,
    'Management training', 4,
    'Other', 3
  ),
  ARRAY['Interest income/shared revenues and principal repayment', 'Strategic sale/merger of company', 'Financial investor take-out'],
  'our initial fund has 16 exits',
  jsonb_build_object(
    'Fundraising with access to global LPs', 5,
    'Fundraising with access to local LPs', 5,
    'Fundraising with access to warehousing capital', 4,
    'Fundraising with access to grant capital for vehicle OPEX', 5,
    'Fundraising with access to TA support', 5,
    'Fund economics', 5,
    'Fund structuring', 5,
    'Investment process (eg origination, due diligence, structuring, closing)', 3,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 4,
    'Fund staff/Human capital management and development', 4,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 3,
    'Exit/monetization opportunities', 4,
    'Legal/regulatory support', 3,
    'Application of impact metrics', 3,
    'Other', 3
  ),
  'Somewhat negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - slight impact',
    'Ability to pay staff salaries', 'To date - slight impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - slight impact',
    'Ability to pay existing business loans', 'To date - slight impact',
    'Access to supply inputs / raw materials', 'To date - high impact',
    'Ability to pay for raw inputs / raw materials', 'To date - slight impact',
    'Need to pivot business model', 'To date - slight impact'
  ),
  ARRAY['No'],
  ARRAY['New pipeline investments through new vehicle'],
  ARRAY['No change planned'],
  '4',
  jsonb_build_object(
    'Fund Economics', 4,
    'LP Profiles', 4,
    'Market Data', 3,
    'Purpose Definition', 2,
    'Access to Capital (DfID proposal)', 2
  ),
  'Creating collaborative fund syndications',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 3,
    'COVID-19 Response (peer discussion)', 3,
    'Fundraising (presentations from I&P, Capria & DGGF)', 2,
    'Portfolio Support (presentations from 10-Xe and AMI)', 3,
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 4,
    'Fundraising 2.0 (peer discussion)', 3,
    'Human Capital (peer discussion)', 3,
    'Co-investing workshop with ADAP (peer discussion)', 3,
    'Fundraising 3.0 – local capital (peer discussion)', 3,
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 3,
    'Mentoring Pilot Kick-off', 2
  ),
  'N/A',
  'WhatsApp only',
  jsonb_build_object(
    'Peer connections and peer learning', 1,
    'Advocacy for early stage investing ', 1,
    'Raised profile/visibility (individual or collective)', 1,
    'Systems change to drive more capital towards local capital providers', 3
  ),
  false,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 1,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 2,
    'Mentoring program (expert led)', 1,
    'Mentoring program (peer-led)', 1,
    'Webinars with peer-to-peer feedback sessions', 1,
    'Webinars with expert-led feedback sessions', 1,
    'Fundraising Readiness Advisory Program for fund managers', 1,
    'Investment readiness for portfolio companies', 1,
    'Fund Manager Portal (ie library of resources, templates etc)', 3,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 1,
    'Joint back office between actively investing fund managers', 1
  ),
  'Yes, as a mentee',
  ARRAY['No']::text[],
  '',
  '2021-02-08 22:20:01'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'lkefela@gmail.com';

COMMIT;
