BEGIN;

-- Delete any existing 2021 survey response for Lilian Mramba
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'Lmramba@gbfund.org');

-- Insert complete 2021 survey response for Lilian Mramba
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Grassroots Business Fund',
  'Lilian Mramba',
  'Africa Regional Director',
  ARRAY['Africa - East Africa'],
  ARRAY['Africa - East Africa'],
  'Second fund/vehicle',
  'Legal entity, 1st close (or equivalent), First investment',
  'As of March 2020',
  'As of December 2020',
  'As of March 2020',
  'As of December 2020',
  '',
  ARRAY['Closed-end fund', 'Second vehicle will be open-ended'],
  'Current',
  'Target',
  '6-7 years',
  ARRAY['Dynamic Enterprises (proven business models operating in established industries with moderate growth potential)'],
  ARRAY['Growth (established business in need of funds for expansion, assets, working capital etc)'],
  ARRAY['Major capital investments (facilities, production equipment, fleet/logistics, etc.)', 'Inventory and working capital requirements'],
  ARRAY['High Net Worth Individuals (HNWIs)', 'Development Finance Institutions (DFIs)', 'Impact investing family offices'],
  'Targeted',
  'Targeted',
  'Balanced impact/financial return',
  ARRAY['Gender', 'Climate / green ventures'],
  true,
  'First',
  'Second',
  'Third',
  ARRAY['Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration']::text[],
  ARRAY['Women ownership/participation interest is ≥ 50%', 'Female staffing is ≥ 50%', 'Provide specific reporting on gender related indicators for your investors/funders', 'Require specific reporting on gender related indicators by your investees/borrowers']::text[],
  ARRAY[]::text[],
  'Your investment amount, Total raise by portfolio company',
  'Your investment amount, Total raise by portfolio company',
  ARRAY['Mezzanine debt'],
  ARRAY['Agriculture / Food supply chain'],
  '0',
  '6-10',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 1,
    'Fundraising including access to working capital resources', 3,
    'Strategic / organizational planning', 2,
    'Product/services proof of concept /market share / competitor positioning', 5,
    'Human capital management – hiring/retention/training', 3,
    'Technology (CRM, MIS, telecommunications, etc)', 5,
    'Legal / regulatory', 5,
    'Operations/ production / facilities and infrastructure', 4,
    'Management training', 2,
    'Other', 5
  ),
  ARRAY['Other types of self-liquidating repayment structures'],
  '10-14',
  jsonb_build_object(
    'Fundraising with access to global LPs', 2,
    'Fundraising with access to local LPs', 1,
    'Fundraising with access to warehousing capital', 3,
    'Fundraising with access to grant capital for vehicle OPEX', 1,
    'Fundraising with access to TA support', 5,
    'Fund economics', 2,
    'Fund structuring', 3,
    'Investment process (eg origination, due diligence, structuring, closing)', 1,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 5,
    'Fund staff/Human capital management and development', 2,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 3,
    'Exit/monetization opportunities', 5,
    'Legal/regulatory support', 5,
    'Application of impact metrics', 2,
    'Other', 3
  ),
  'Somewhat negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - slight impact',
    'Ability to pay staff salaries', 'To date - slight impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - high impact',
    'Ability to pay existing business loans', 'To date - high impact',
    'Access to supply inputs / raw materials', 'To date - slight impact',
    'Ability to pay for raw inputs / raw materials', 'To date - slight impact',
    'Need to pivot business model', 'To date - slight impact'
  ),
  ARRAY['Yes, government support (financial)'],
  ARRAY['New pipeline investments through new vehicle'],
  ARRAY['We are exiting current fund'],
  '3',
  jsonb_build_object(
    'Fund Economics', 'N/A',
    'LP Profiles', 'N/A',
    'Market Data', 'N/A',
    'Purpose Definition', 'N/A',
    'Access to Capital (DfID proposal)', 'N/A'
  ),
  'Whatsapp is the most accessible format for me',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 1,
    'Fundraising (presentations from I&P, Capria & DGGF)', 'N/A',
    'Portfolio Support (presentations from 10-Xe and AMI)', 'N/A',
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 'N/A',
    'Fundraising 2.0 (peer discussion)', 'N/A',
    'Human Capital (peer discussion)', 'N/A',
    'Co-investing workshop with ADAP (peer discussion)', 'N/A',
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 'N/A',
    'Mentoring Pilot Kick-off', 'N/A'
  ),
  'I''d love to see something that talks about the climate + gender nexus and how to operationalize it in funds',
  'WhatsApp only',
  jsonb_build_object(
    'Peer connections and peer learning', 'N/A',
    'Advocacy for early stage investing ', 'N/A',
    'Raised profile/visibility (individual or collective)', 'N/A',
    'Systems change to drive more capital towards local capital providers', 'N/A'
  ),
  true,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 3,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 2,
    'Mentoring program (expert led)', 2,
    'Mentoring program (peer-led)', 2,
    'Webinars with peer-to-peer feedback sessions', 3,
    'Webinars with expert-led feedback sessions', 2,
    'Fundraising Readiness Advisory Program for fund managers', 1,
    'Investment readiness for portfolio companies', 3,
    'Fund Manager Portal (ie library of resources, templates etc)', 2,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 1,
    'Joint back office between actively investing fund managers', 3
  ),
  'No',
  ARRAY['No']::text[],
  '',
  '2021-02-08 17:23:33'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'Lmramba@gbfund.org';

COMMIT;
