BEGIN;

-- Delete any existing 2021 survey response for Lisbeth Zacho
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'lsz@nordicimpactfunds.com');

-- Insert complete 2021 survey response for Lisbeth Zacho
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Nordic Impact Funds',
  'Lisbeth Zacho',
  'Managing Partner',
  ARRAY['Africa - East Africa'],
  ARRAY['Africa - East Africa'],
  'Closed ended - fundraising',
  'Legal entity, First investment',
  'Not yet achieved',
  'Not yet achieved',
  'As of March 2020',
  'As of December 2020',
  '',
  ARRAY['Closed-end fund'],
  'Current',
  'Target',
  '6-7 years',
  ARRAY['Dynamic Enterprises (proven business models operating in established industries with moderate growth potential)', 'Niche Ventures (innovative products/services targeting niche markets with growth ambitions)', 'High-Growth Ventures (disruptive business models targeting large markets with high growth potential)'],
  ARRAY['Early stage / seed (early revenue, product/service development, funds needed to expand business model)', 'Growth (established business in need of funds for expansion, assets, working capital etc)'],
  ARRAY['Major capital investments (facilities, production equipment, fleet/logistics, etc.)', 'Enterprise growth capital (e.g. intangible investments such as staff build-out, expanded sales & marketing capabilities, new markets, operational and support systems, etc.)', 'Inventory and working capital requirements'],
  ARRAY['Local pension funds', 'High Net Worth Individuals (HNWIs)', 'Development Finance Institutions (DFIs)', 'Impact investing family offices'],
  'Targeted',
  'Achieved in most recent reporting period',
  'Impact investing (positive screening), Impact first investing (impact outcomes intentionally)',
  ARRAY['Gender', 'Climate / green ventures'],
  true,
  'First',
  'Others',
  'Second',
  ARRAY['Investment Consideration']::text[],
  ARRAY['Majority women ownership (>50%)', 'Greater than 33% of women in senior management', 'Women represent at least 33% - 50% of direct workforce', 'Women represent at least 33% - 50% of indirect workforce (e.g. supply chain/distribution channel, or both)', 'Have policies in place that promote gender equality (e.g. equal compensation)', 'Women are target beneficiaries of the product/service', 'Enterprise reports on specific gender related indicators to investors', 'Board member female representation (>33%)', 'Female CEO']::text[],
  ARRAY['Women ownership/participation interest is ≥ 50%', 'Women representation on the board/investment committee is ≥ 50', 'Provide specific reporting on gender related indicators for your investors/funders', 'Require specific reporting on gender related indicators by your investees/borrowers']::text[],
  'Your investment amount',
  'Your investment amount, Total raise by portfolio company',
  ARRAY['Common equity', 'Convertible notes'],
  ARRAY['Agriculture / Food supply chain', 'Financial Inclusion / Insurance / Fintech', 'Water and Sanitation'],
  '2-3',
  '3-5',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 2,
    'Fundraising including access to working capital resources', 2,
    'Strategic / organizational planning', 1,
    'Product/services proof of concept /market share / competitor positioning', 3,
    'Human capital management – hiring/retention/training', 1,
    'Technology (CRM, MIS, telecommunications, etc)', 3,
    'Legal / regulatory', 3,
    'Operations/ production / facilities and infrastructure', 4,
    'Management training', 1,
    'Other', 4
  ),
  ARRAY['Strategic sale/merger of company', 'Financial investor take-out'],
  '0',
  jsonb_build_object(
    'Fundraising with access to global LPs', 1,
    'Fundraising with access to local LPs', 3,
    'Fundraising with access to warehousing capital', 1,
    'Fundraising with access to grant capital for vehicle OPEX', 2,
    'Fundraising with access to TA support', 1,
    'Fund economics', 4,
    'Fund structuring', 4,
    'Investment process (eg origination, due diligence, structuring, closing)', 4,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 2,
    'Fund staff/Human capital management and development', 3,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 4,
    'Exit/monetization opportunities', 4,
    'Legal/regulatory support', 5,
    'Application of impact metrics', 2,
    'Other', 3
  ),
  'Somewhat negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - slight impact',
    'Ability to pay staff salaries', 'To date - no impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - no impact',
    'Ability to pay existing business loans', 'To date - no impact',
    'Access to supply inputs / raw materials', 'To date - no impact',
    'Ability to pay for raw inputs / raw materials', 'To date - no impact',
    'Need to pivot business model', 'To date - slight impact'
  ),
  ARRAY['No'],
  ARRAY['New pipeline investments through existing vehicle', 'Technical assistance to support portfolio enterprises'],
  ARRAY['Seek increased access to new LP funds locally', 'Seek increased access to new LP funds internationally', 'Build new partnerships for joint co-investment opportunities, expand pipeline opportunities'],
  '2',
  jsonb_build_object(
    'Fund Economics', 3,
    'LP Profiles', 2,
    'Market Data', 3,
    'Purpose Definition', 4,
    'Access to Capital (DfID proposal)', 1
  ),
  'Pipeline building',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 1,
    'COVID-19 Response (peer discussion)', 'N/A',
    'Fundraising (presentations from I&P, Capria & DGGF)', 'N/A',
    'Portfolio Support (presentations from 10-Xe and AMI)', 'N/A',
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 'N/A',
    'Fundraising 2.0 (peer discussion)', 'N/A',
    'Human Capital (peer discussion)', 'N/A',
    'Co-investing workshop with ADAP (peer discussion)', 'N/A',
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 'N/A',
    'Mentoring Pilot Kick-off', 2
  ),
  'Investment landscape in specific regions. Co-investment workshops on specific topics/sectors. Gender lens pipeline etc....',
  'WhatsApp only',
  jsonb_build_object(
    'Peer connections and peer learning', 1,
    'Advocacy for early stage investing ', 1,
    'Raised profile/visibility (individual or collective)', 3,
    'Systems change to drive more capital towards local capital providers', 3
  ),
  false,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 1,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 1,
    'Mentoring program (expert led)', 2,
    'Mentoring program (peer-led)', 2,
    'Webinars with peer-to-peer feedback sessions', 2,
    'Webinars with expert-led feedback sessions', 2,
    'Fundraising Readiness Advisory Program for fund managers', 2,
    'Investment readiness for portfolio companies', 2,
    'Fund Manager Portal (ie library of resources, templates etc)', 1,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 1,
    'Joint back office between actively investing fund managers', 3
  ),
  'Yes, as a mentee',
  ARRAY['No'],
  'Thanks so much for your support!',
  '2021-02-02 21:35:30'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'lsz@nordicimpactfunds.com';

COMMIT;
