BEGIN;

-- Delete any existing 2021 survey response for Olivier Furdelle
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'olivier.furdelle@terangacapital.com');

-- Insert complete 2021 survey response for Olivier Furdelle
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Teranga Capital',
  'Olivier Furdelle',
  'Managing Director',
  ARRAY['Africa - West Africa'],
  ARRAY['Africa - West Africa'],
  'Open-ended - achieved equivalent of 1st close with sufficient committed funds to cover fund economics',
  'Legal entity, 1st close (or equivalent), First investment',
  '1st close (or equivalent)',
  'First investment',
  'As of March 2020',
  'As of December 2020',
  '',
  ARRAY['Open-ended vehicle / Limited liability company or equivalent'],
  'Current',
  'Target',
  '4-5 years',
  ARRAY['Dynamic Enterprises (proven business models operating in established industries with moderate growth potential)', 'Niche Ventures (innovative products/services targeting niche markets with growth ambitions)', 'High-Growth Ventures (disruptive business models targeting large markets with high growth potential)'],
  ARRAY['Early stage / seed (early revenue, product/service development, funds needed to expand business model)', 'Growth (established business in need of funds for expansion, assets, working capital etc)'],
  ARRAY['Small ticket tangible assets (e.g. computers, routers, mobile and connectivity systems, office equipment, etc.)', 'Major capital investments (facilities, production equipment, fleet/logistics, etc.)', 'Enterprise growth capital (e.g. intangible investments such as staff build-out, expanded sales & marketing capabilities, new markets, operational and support systems, etc.)', 'Inventory and working capital requirements'],
  ARRAY['Fund partners', 'High Net Worth Individuals (HNWIs)', 'Impact investing family offices', 'Donors/philanthropy', 'Corporates'],
  'Targeted',
  'Targeted',
  'Balanced impact/financial return, Impact investing (positive screening)',
  ARRAY['Job creation', 'N/A'],
  false,
  NULL,
  NULL,
  NULL,
  ARRAY['Investment Consideration']::text[],
  ARRAY['Majority women ownership (>50%)', 'Greater than 33% of women in senior management', 'Women represent at least 33% - 50% of direct workforce', 'Women represent at least 33% - 50% of indirect workforce (e.g. supply chain/distribution channel, or both)', 'Have policies in place that promote gender equality (e.g. equal compensation)', 'Women are target beneficiaries of the product/service', 'Enterprise reports on specific gender related indicators to investors', 'Board member female representation (>33%)', 'Female CEO']::text[],
  ARRAY['Women representation on the board/investment committee is ≥ 50', 'Female staffing is ≥ 50%', 'Provide specific reporting on gender related indicators for your investors/funders', 'Board member female representation (>25%) in portfolio companies']::text[],
  'Your investment amount, Total raise by portfolio company',
  'Total raise by portfolio company',
  ARRAY['Common equity', 'Preferred equity (e.g. certain rights above those available to common equity holders)', 'Convertible notes', 'Shared revenue/earnings instruments', 'SAFEs', 'shareholders loans for working capital'],
  ARRAY['Sector agnostic'],
  '4-5',
  '6-10',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 1,
    'Fundraising including access to working capital resources', 1,
    'Strategic / organizational planning', 1,
    'Product/services proof of concept /market share / competitor positioning', 1,
    'Human capital management – hiring/retention/training', 2,
    'Technology (CRM, MIS, telecommunications, etc)', 3,
    'Legal / regulatory', 2,
    'Operations/ production / facilities and infrastructure', 2,
    'Management training', 1,
    'Other', 1
  ),
  ARRAY['Interest income/shared revenues and principal repayment', 'Other types of self-liquidating repayment structures', 'Strategic sale/merger of company', 'Financial investor take-out'],
  '0',
  jsonb_build_object(
    'Fundraising with access to global LPs', 3,
    'Fundraising with access to local LPs', 1,
    'Fundraising with access to warehousing capital', 1,
    'Fundraising with access to grant capital for vehicle OPEX', 1,
    'Fundraising with access to TA support', 1,
    'Fund economics', 3,
    'Fund structuring', 4,
    'Investment process (eg origination, due diligence, structuring, closing)', 1,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 2,
    'Fund staff/Human capital management and development', 1,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 4,
    'Exit/monetization opportunities', 3,
    'Legal/regulatory support', 3,
    'Application of impact metrics', 3,
    'Other', 3
  ),
  'Significant negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - slight impact',
    'Ability to pay staff salaries', 'To date - high impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - high impact',
    'Ability to pay existing business loans', 'To date - high impact',
    'Access to supply inputs / raw materials', 'To date - high impact',
    'Ability to pay for raw inputs / raw materials', 'To date - high impact',
    'Need to pivot business model', 'To date - high impact'
  ),
  ARRAY['Yes, grant funding (financial)', 'Yes, non-financial assistance'],
  ARRAY['Stabilize operations of existing portfolio companies', 'New pipeline investments through existing vehicle', 'Technical assistance to support portfolio enterprises'],
  ARRAY['Seek increased access to new LP funds locally', 'Increase application of alternative debt instruments (e.g. mezzanine debt, convertible debt, or shared revenue instruments)', 'Build new partnerships for joint co-investment opportunities, expand pipeline opportunities', 'diversification of activities to enhance business model economics'],
  '2',
  jsonb_build_object(
    'Fund Economics', 2,
    'LP Profiles', 3,
    'Market Data', 3,
    'Purpose Definition', 1,
    'Access to Capital (DfID proposal)', 'N/A'
  ),
  'Not at this stage',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 1,
    'Fundraising (presentations from I&P, Capria & DGGF)', 2,
    'Portfolio Support (presentations from 10-Xe and AMI)', 2,
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 1,
    'Fundraising 2.0 (peer discussion)', 1,
    'Human Capital (peer discussion)', 2,
    'Co-investing workshop with ADAP (peer discussion)', 1,
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 'N/A',
    'Mentoring Pilot Kick-off', 'N/A'
  ),
  'Not at this stage',
  'Both Slack (eg for working groups etc) and WhatsApp (eg for more time sensitive communications)',
  jsonb_build_object(
    'Peer connections and peer learning', 1,
    'Advocacy for early stage investing ', 3,
    'Raised profile/visibility (individual or collective)', 2,
    'Systems change to drive more capital towards local capital providers', 3
  ),
  true,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 1,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 2,
    'Mentoring program (expert led)', 1,
    'Mentoring program (peer-led)', 1,
    'Webinars with peer-to-peer feedback sessions', 1,
    'Webinars with expert-led feedback sessions', 1,
    'Fundraising Readiness Advisory Program for fund managers', 3,
    'Investment readiness for portfolio companies', 3,
    'Fund Manager Portal (ie library of resources, templates etc)', 2,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 1,
    'Joint back office between actively investing fund managers', 2
  ),
  'Yes, as a mentor, Yes, as a mentee',
  ARRAY['Yes, open ended vehicles', 'Yes, early stage equity', 'Yes, angel investing / engaging local co-investors'],
  'not at this stage',
  '2021-02-02 19:07:19'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'olivier.furdelle@terangacapital.com';

COMMIT;
