BEGIN;

-- Delete any existing 2021 survey response for Shiva Shanker
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'shiva@ankurcapital.com');

-- Insert complete 2021 survey response for Shiva Shanker
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Ankur Capital',
  'Shiva Shanker',
  'VP',
  ARRAY['Asia - South Asia'],
  ARRAY['Asia - South Asia'],
  'Closed ended - completed second close, Second fund/vehicle',
  'Legal entity',
  '1st close (or equivalent), First investment',
  'As of March 2020',
  'As of December 2020',
  'As of March 2020',
  '',
  ARRAY['Closed-end fund'],
  'Current',
  'Target',
  '4-5 years',
  ARRAY['High-Growth Ventures (disruptive business models targeting large markets with high growth potential)'],
  ARRAY['Start-up / pre-seed (pre-revenue, concept and business plan development)', 'Early stage / seed (early revenue, product/service development, funds needed to expand business model)'],
  ARRAY['Venture launch – invest in initial staff, product/services development and market acceptance'],
  ARRAY['Fund partners', 'High Net Worth Individuals (HNWIs)', 'Development Finance Institutions (DFIs)', 'Impact investing family offices'],
  'Targeted',
  'Targeted',
  'Financial return first, Responsible/ESG investing (negative screening)',
  ARRAY['Benefit to underserved as defined by region or Income'],
  false,
  NULL,
  NULL,
  NULL,
  ARRAY['Investment Consideration']::text[],
  ARRAY['Women ownership/participation interest is ≥ 50%', 'Women representation on the board/investment committee is ≥ 50', 'Female staffing is ≥ 50%', 'Provide specific reporting on gender related indicators for your investors/funders', 'Require specific reporting on gender related indicators by your investees/borrowers']::text[],
  ARRAY[]::text[],
  'Your investment amount, Total raise by portfolio company',
  'Your investment amount, Total raise by portfolio company',
  ARRAY['Preferred equity (e.g. certain rights above those available to common equity holders)'],
  ARRAY['Agriculture / Food supply chain', 'Distribution / Logistics', 'Education', 'Financial Inclusion / Insurance / Fintech', 'Healthcare', 'Technology / ICT / Telecommunications'],
  '4-5',
  '6-10',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 2,
    'Fundraising including access to working capital resources', 1,
    'Strategic / organizational planning', 1,
    'Product/services proof of concept /market share / competitor positioning', 2,
    'Human capital management – hiring/retention/training', 1,
    'Technology (CRM, MIS, telecommunications, etc)', 2,
    'Legal / regulatory', 3,
    'Operations/ production / facilities and infrastructure', 3,
    'Management training', 2,
    'Other', 5
  ),
  ARRAY['Strategic sale/merger of company', 'Management buyout', 'Financial investor take-out'],
  '1-4',
  jsonb_build_object(
    'Fundraising with access to global LPs', 1,
    'Fundraising with access to local LPs', 4,
    'Fundraising with access to warehousing capital', 4,
    'Fundraising with access to grant capital for vehicle OPEX', 4,
    'Fundraising with access to TA support', 1,
    'Fund economics', 2,
    'Fund structuring', 2,
    'Investment process (eg origination, due diligence, structuring, closing)', 1,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 3,
    'Fund staff/Human capital management and development', 3,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 3,
    'Exit/monetization opportunities', 2,
    'Legal/regulatory support', 4,
    'Application of impact metrics', 2,
    'Other', 5
  ),
  'Neither positive nor negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - slight impact',
    'Ability to pay staff salaries', 'To date - slight impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - slight impact',
    'Ability to pay existing business loans', 'Anticipate future impact',
    'Access to supply inputs / raw materials', 'To date - high impact',
    'Ability to pay for raw inputs / raw materials', 'To date - slight impact',
    'Need to pivot business model', 'To date - high impact'
  ),
  ARRAY['No'],
  ARRAY['Growth capital for existing portfolio to increase market share', 'Growth capital for existing portfolio to enter new markets/expand business line(s)', 'New pipeline investments through existing vehicle'],
  ARRAY['Seek increased access to new LP funds locally', 'Seek increased access to new LP funds internationally', 'Increase application of alternative debt instruments (e.g. mezzanine debt, convertible debt, or shared revenue instruments)', 'Increase use of data and technology to facilitate investment decisions', 'Build new partnerships for joint co-investment opportunities, expand pipeline opportunities'],
  '2',
  jsonb_build_object(
    'Fund Economics', 1,
    'LP Profiles', 3,
    'Market Data', 2,
    'Purpose Definition', 2,
    'Access to Capital (DfID proposal)', 3
  ),
  'No',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 2,
    'Fundraising (presentations from I&P, Capria & DGGF)', 2,
    'Portfolio Support (presentations from 10-Xe and AMI)', 'N/A',
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 'N/A',
    'Fundraising 2.0 (peer discussion)', 'N/A',
    'Human Capital (peer discussion)', 2,
    'Co-investing workshop with ADAP (peer discussion)', 1,
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 2,
    'Mentoring Pilot Kick-off', 'N/A'
  ),
  'N/A',
  'Both Slack (eg for working groups etc) and WhatsApp (eg for more time sensitive communications)',
  jsonb_build_object(
    'Peer connections and peer learning', 1,
    'Advocacy for early stage investing ', 2,
    'Raised profile/visibility (individual or collective)', 3,
    'Systems change to drive more capital towards local capital providers', 3
  ),
  true,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 2,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 1,
    'Mentoring program (expert led)', 3,
    'Mentoring program (peer-led)', 3,
    'Webinars with peer-to-peer feedback sessions', 1,
    'Webinars with expert-led feedback sessions', 2,
    'Fundraising Readiness Advisory Program for fund managers', 3,
    'Investment readiness for portfolio companies', 3,
    'Fund Manager Portal (ie library of resources, templates etc)', 2,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 1,
    'Joint back office between actively investing fund managers', 2
  ),
  'Not sure',
  ARRAY['No']::text[],
  '',
  '2021-02-08 16:32:23'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'shiva@ankurcapital.com';

COMMIT;