BEGIN;

-- Delete any existing 2021 survey response for Tony Chen
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'tony@kinyungu.com');

-- Insert complete 2021 survey response for Tony Chen
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Kinyungu Ventures',
  'Tony Chen',
  'Managing Director',
  ARRAY['US/Europe', 'Africa - East Africa'],
  ARRAY['Africa - East Africa'],
  'Open ended - fundraising and heading towards equivalent of 1st close (i.e. lack sufficient committed funds to cover fund economics)',
  'First investment',
  'Not yet achieved',
  'As of March 2020',
  'As of March 2020',
  'As of December 2020',
  'still TBD on structure',
  ARRAY['Preferred equity (e.g. certain rights above those available to common equity holders)', 'Convertible notes', 'Senior debt', 'SAFEs'],
  'Current',
  'TBD',
  '1-3 years',
  ARRAY['Niche Ventures (innovative products/services targeting niche markets with growth ambitions)', 'High-Growth Ventures (disruptive business models targeting large markets with high growth potential)', 'resilient businesses'],
  ARRAY['Early stage / seed (early revenue, product/service development, funds needed to expand business model)', 'Growth (established business in need of funds for expansion, assets, working capital etc)'],
  ARRAY['Venture launch – invest in initial staff, product/services development and market acceptance'],
  ARRAY['High Net Worth Individuals (HNWIs)', 'Angel network', 'Impact investing family offices', 'Donors/philanthropy'],
  '',
  'Targeted',
  'Impact investing (positive screening)',
  ARRAY['N/A'],
  false,
  NULL,
  NULL,
  NULL,
  ARRAY['Investment Consideration'],
  ARRAY['Women ownership/participation interest is ≥ 50%'],
  ARRAY[]::text[],
  'Your investment amount',
  'Your investment amount, Total raise by portfolio company, Total raise by portfolio company',
  ARRAY['Preferred equity (e.g. certain rights above those available to common equity holders)', 'Convertible notes', 'Senior debt', 'SAFEs'],
  ARRAY['Sector agnostic'],
  '2-3',
  '< or = 2',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 3,
    'Fundraising including access to working capital resources', 2,
    'Strategic / organizational planning', 3,
    'Product/services proof of concept /market share / competitor positioning', 4,
    'Human capital management – hiring/retention/training', 1,
    'Technology (CRM, MIS, telecommunications, etc)', 3,
    'Legal / regulatory', 2,
    'Operations/ production / facilities and infrastructure', 4,
    'Management training', 2,
    'Other', 2
  ),
  ARRAY['Financial investor take-out'],
  '1-4',
  jsonb_build_object(
    'Fundraising with access to global LPs', 1,
    'Fundraising with access to local LPs', 1,
    'Fundraising with access to warehousing capital', 4,
    'Fundraising with access to grant capital for vehicle OPEX', 2,
    'Fundraising with access to TA support', 2,
    'Fund economics', 2,
    'Fund structuring', 1,
    'Investment process (eg origination, due diligence, structuring, closing)', 3,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 3,
    'Fund staff/Human capital management and development', 3,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 3,
    'Exit/monetization opportunities', 3,
    'Legal/regulatory support', 3,
    'Application of impact metrics', 3,
    'Other', 3
  ),
  'Somewhat negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - high impact',
    'Ability to pay staff salaries', 'To date - high impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - high impact',
    'Ability to pay existing business loans', 'To date - high impact',
    'Access to supply inputs / raw materials', 'To date - high impact',
    'Ability to pay for raw inputs / raw materials', 'To date - high impact',
    'Need to pivot business model', 'To date - high impact'
  ),
  ARRAY['No'],
  ARRAY['New pipeline investments through new vehicle', 'Technical assistance to support portfolio enterprises'],
  ARRAY['Seek increased access to new LP funds locally', 'Seek increased access to new LP funds internationally', 'Increase use of technology in order to lower fund operational costs', 'Build new partnerships for joint co-investment opportunities, expand pipeline opportunities'],
  '2',
  jsonb_build_object(
    'Fund Economics', 'N/A',
    'LP Profiles', 'N/A',
    'Market Data', 1,
    'Purpose Definition', 'N/A',
    'Access to Capital (DfID proposal)', 1
  ),
  'none',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 1,
    'Fundraising (presentations from I&P, Capria & DGGF)', 1,
    'Portfolio Support (presentations from 10-Xe and AMI)', 2
  ),
  'N/A',
  'WhatsApp only',
  jsonb_build_object(
    'Peer connections and peer learning', 1,
    'Advocacy for early stage investing ', 2,
    'Raised profile/visibility (individual or collective)', 2,
    'Systems change to drive more capital towards local capital providers', 3
  ),
  true,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 1,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 2,
    'Mentoring program (expert led)', 3,
    'Mentoring program (peer-led)', 3,
    'Webinars with peer-to-peer feedback sessions', 1,
    'Webinars with expert-led feedback sessions', 1,
    'Fundraising Readiness Advisory Program for fund managers', 1,
    'Investment readiness for portfolio companies', 2,
    'Fund Manager Portal (ie library of resources, templates etc)', 2,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 2
  ),
  'Not sure',
  ARRAY['No'],
  NULL,
  '2021-01-25 15:14:00'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'tony@kinyungu.com';

COMMIT;
