BEGIN;

-- Delete any existing 2021 survey response for Valerie Fraser
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'vfraser@jengacapital.com');

-- Insert complete 2021 survey response for Valerie Fraser
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Jenga Capital',
  'Valerie Frser',
  'Director',
  ARRAY['Africa - East Africa'],
  ARRAY['Africa - East Africa'],
  'Open-ended - achieved equivalent of 1st close with sufficient committed funds to cover fund economics',
  'Legal entity',
  'Legal entity',
  'First investment',
  'As of March 2020',
  'As of December 2020',
  NULL,
  ARRAY['Open-ended vehicle / Limited liability company or equivalent'],
  'Current',
  'Target',
  '1-3 years',
  ARRAY['Livelihood Sustaining Enterprises (formal/informal family run businesses targeting incremental growth)', 'Dynamic Enterprises (proven business models operating in established industries with moderate growth potential)'],
  ARRAY['Early stage / seed (early revenue, product/service development, funds needed to expand business model)', 'Growth (established business in need of funds for expansion, assets, working capital etc)'],
  ARRAY['Major capital investments (facilities, production equipment, fleet/logistics, etc.)', 'Enterprise growth capital (e.g. intangible investments such as staff build-out, expanded sales & marketing capabilities, new markets, operational and support systems, etc.)', 'Inventory and working capital requirements'],
  ARRAY['High Net Worth Individuals (HNWIs)'],
  'Achieved in most recent reporting period',
  'Targeted',
  'Financial return first',
  ARRAY['N/A'],
  false,
  NULL,
  NULL,
  NULL,
  ARRAY['Investment Consideration', 'Investment Consideration', 'Investment Consideration'],
  ARRAY['Women representation on the board/investment committee is ≥ 50', 'Female staffing is ≥ 50%'],
  ARRAY[]::text[],
  'Your investment amount',
  'Your investment amount',
  ARRAY['Senior debt', 'Mezzanine debt'],
  ARRAY['Agriculture / Food supply chain'],
  '1',
  '< or = 2',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 2,
    'Fundraising including access to working capital resources', 1,
    'Strategic / organizational planning', 2,
    'Product/services proof of concept /market share / competitor positioning', 4,
    'Human capital management – hiring/retention/training', 3,
    'Technology (CRM, MIS, telecommunications, etc)', 3,
    'Legal / regulatory', 3,
    'Operations/ production / facilities and infrastructure', 2,
    'Management training', 3,
    'Other', 5
  ),
  ARRAY['Interest income/shared revenues and principal repayment'],
  '1-4',
  jsonb_build_object(
    'Fundraising with access to global LPs', 4,
    'Fundraising with access to local LPs', 4,
    'Fundraising with access to warehousing capital', 4,
    'Fundraising with access to grant capital for vehicle OPEX', 4,
    'Fundraising with access to TA support', 5,
    'Fund economics', 1,
    'Fund structuring', 1,
    'Investment process (eg origination, due diligence, structuring, closing)', 2,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 2,
    'Fund staff/Human capital management and development', 1,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 2,
    'Exit/monetization opportunities', 2,
    'Legal/regulatory support', 2,
    'Application of impact metrics', 1,
    'Other', 5
  ),
  'Neither positive nor negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - high impact',
    'Ability to pay staff salaries', 'To date - no impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - no impact',
    'Ability to pay existing business loans', 'To date - no impact',
    'Access to supply inputs / raw materials', 'To date - slight impact',
    'Ability to pay for raw inputs / raw materials', 'To date - no impact',
    'Need to pivot business model', 'To date - no impact'
  ),
  ARRAY['No'],
  ARRAY['N/A - have no plans to raise capital in 2021'],
  ARRAY['Increase application of alternative debt instruments (e.g. mezzanine debt, convertible debt, or shared revenue instruments)', 'Increase use of technology in order to lower fund operational costs', 'Increase use of data and technology to facilitate investment decisions', 'Build new partnerships for joint co-investment opportunities, expand pipeline opportunities'],
  '2',
  jsonb_build_object(
    'Fund Economics', 5,
    'LP Profiles', 'N/A',
    'Market Data', 'N/A',
    'Purpose Definition', 'N/A',
    'Access to Capital (DfID proposal)', 'N/A'
  ),
  'Legal Support',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 'N/A',
    'Fundraising (presentations from I&P, Capria & DGGF)', 'N/A',
    'Portfolio Support (presentations from 10-Xe and AMI)', 'N/A',
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 'N/A',
    'Fundraising 2.0 (peer discussion)', 'N/A',
    'Human Capital (peer discussion)', 'N/A',
    'Co-investing workshop with ADAP (peer discussion)', 'N/A',
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 'N/A',
    'Mentoring Pilot Kick-off', 'N/A'
  ),
  'n/a',
  'WhatsApp only',
  jsonb_build_object(
    'Peer connections and peer learning', 1,
    'Advocacy for early stage investing ', 4,
    'Raised profile/visibility (individual or collective)', 1,
    'Systems change to drive more capital towards local capital providers', 2
  ),
  false,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 1,
    'TA facility to support early fund economics and activities', 3,
    'Advocacy for the early-stage investing ecosystem', 3,
    'Mentoring program (expert led)', 2,
    'Mentoring program (peer-led)', 2,
    'Webinars with peer-to-peer feedback sessions', 2,
    'Webinars with expert-led feedback sessions', 2,
    'Fundraising Readiness Advisory Program for fund managers', 1,
    'Investment readiness for portfolio companies', 1,
    'Fund Manager Portal (ie library of resources, templates etc)', 1,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 1,
    'Joint back office between actively investing fund managers', 1
  ),
  'Yes, as a mentee',
  ARRAY['No'],
  NULL,
  '2021-01-28 09:44:31'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'vfraser@jengacapital.com';

COMMIT;
