BEGIN;

-- Delete any existing 2021 survey response for William Prothais
DELETE FROM public.survey_responses_2021 
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'william.prothais@uberiscapital.com');

-- Insert complete 2021 survey response for William Prothais
INSERT INTO public.survey_responses_2021 (
  user_id,
  firm_name,
  participant_name,
  role_title,
  team_based,
  geographic_focus,
  fund_stage,
  legal_entity_date,
  first_close_date,
  first_investment_date,
  investments_march_2020,
  investments_december_2020,
  optional_supplement,
  investment_vehicle_type,
  current_fund_size,
  target_fund_size,
  investment_timeframe,
  business_model_targeted,
  business_stage_targeted,
  financing_needs,
  target_capital_sources,
  target_irr_achieved,
  target_irr_targeted,
  impact_vs_financial_orientation,
  explicit_lens_focus,
  report_sustainable_development_goals,
  top_sdg_1,
  top_sdg_2,
  top_sdg_3,
  gender_considerations_investment,
  gender_considerations_requirement,
  gender_fund_vehicle,
  investment_size_your_amount,
  investment_size_total_raise,
  investment_forms,
  target_sectors,
  carried_interest_principals,
  current_ftes,
  portfolio_needs_ranking,
  investment_monetization,
  exits_achieved,
  fund_capabilities_ranking,
  covid_impact_aggregate,
  covid_impact_portfolio,
  covid_government_support,
  raising_capital_2021,
  fund_vehicle_considerations,
  network_value_rating,
  working_groups_ranking,
  new_working_group_suggestions,
  webinar_content_ranking,
  new_webinar_suggestions,
  communication_platform,
  network_value_areas,
  present_connection_session,
  convening_initiatives_ranking,
  participate_mentoring_program,
  present_demystifying_session,
  additional_comments,
  completed_at,
  created_at,
  updated_at
)
SELECT
  u.id,
  'Uberis',
  'William Prothais',
  'Fund Associate',
  ARRAY['Asia - South East Asia'],
  ARRAY['Asia - South East Asia'],
  'Open ended - fundraising and heading towards equivalent of 1st close (i.e. lack sufficient committed funds to cover fund economics)',
  'First investment',
  'Not yet achieved',
  'As of March 2020',
  'As of March 2020',
  'As of December 2020',
  NULL,
  ARRAY['Open-ended vehicle / Limited liability company or equivalent'],
  'Current',
  'Target',
  '1-3 years',
  ARRAY['impactful early stage ventures'],
  ARRAY['Start-up / pre-seed (pre-revenue, concept and business plan development)', 'Early stage / seed (early revenue, product/service development, funds needed to expand business model)'],
  ARRAY['Venture launch – invest in initial staff, product/services development and market acceptance', 'Small ticket tangible assets (e.g. computers, routers, mobile and connectivity systems, office equipment, etc.)'],
  ARRAY['Fund partners', 'High Net Worth Individuals (HNWIs)', 'Angel network', 'Impact investing family offices', 'Donors/philanthropy'],
  'Achieved in most recent reporting period',
  'Targeted',
  'Impact investing (positive screening)',
  ARRAY['Gender', 'Climate / green ventures'],
  true,
  'First',
  'Second',
  'Second',
  ARRAY['Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration', 'Investment Consideration'],
  ARRAY['Provide specific reporting on gender related indicators for your investors/funders'],
  ARRAY[]::text[],
  'Your investment amount',
  'Total raise by portfolio company',
  ARRAY['Common equity', 'Convertible notes'],
  ARRAY['Sector agnostic'],
  '2-3',
  '< or = 2',
  jsonb_build_object(
    'Finance, budgeting, accounting, cash and tax management', 1,
    'Fundraising including access to working capital resources', 1,
    'Strategic / organizational planning', 1,
    'Product/services proof of concept /market share / competitor positioning', 3,
    'Human capital management – hiring/retention/training', 2,
    'Technology (CRM, MIS, telecommunications, etc)', 3,
    'Legal / regulatory', 2,
    'Operations/ production / facilities and infrastructure', 3,
    'Management training', 2,
    'Other', 5
  ),
  ARRAY['Strategic sale/merger of company', 'Financial investor take-out'],
  '0',
  jsonb_build_object(
    'Fundraising with access to global LPs', 2,
    'Fundraising with access to local LPs', 1,
    'Fundraising with access to warehousing capital', 3,
    'Fundraising with access to grant capital for vehicle OPEX', 2,
    'Fundraising with access to TA support', 2,
    'Fund economics', 5,
    'Fund structuring', 5,
    'Investment process (eg origination, due diligence, structuring, closing)', 5,
    'Post investment process (eg monitoring, reporting, exits, Technical Assistance)', 5,
    'Fund staff/Human capital management and development', 5,
    'Back office (financial/impact reporting, accounting, CFO, software, templates, etc)', 5,
    'Exit/monetization opportunities', 5,
    'Legal/regulatory support', 5,
    'Application of impact metrics', 5,
    'Other', 5
  ),
  'Somewhat negative impact',
  jsonb_build_object(
    'Staff attendance', 'To date - slight impact',
    'Customer demand', 'To date - slight impact',
    'Ability to pay staff salaries', 'To date - no impact',
    'Ability to pay fixed operating cost (eg rent, etc.)', 'To date - slight impact',
    'Ability to pay existing business loans', 'To date - slight impact',
    'Access to supply inputs / raw materials', 'To date - slight impact',
    'Ability to pay for raw inputs / raw materials', 'To date - slight impact',
    'Need to pivot business model', 'To date - slight impact'
  ),
  ARRAY['No'],
  ARRAY['Technical assistance to support portfolio enterprises'],
  ARRAY['Seek increased access to new LP funds locally', 'Increase use of data and technology to facilitate investment decisions', 'Build new partnerships for joint co-investment opportunities, expand pipeline opportunities'],
  '2',
  jsonb_build_object(
    'Fund Economics', 2,
    'LP Profiles', 1,
    'Market Data', 3,
    'Purpose Definition', 4,
    'Access to Capital (DfID proposal)', 2
  ),
  'no',
  jsonb_build_object(
    'Gender lens investing (facilitated by Suzanne Biegel)', 'N/A',
    'COVID-19 Response (peer discussion)', 'N/A',
    'Fundraising (presentations from I&P, Capria & DGGF)', 'N/A',
    'Portfolio Support (presentations from 10-Xe and AMI)', 'N/A',
    'SGB COVID-19 Capital Bridge Facility (presentation from CFF)', 'N/A',
    'Fundraising 2.0 (peer discussion)', 'N/A',
    'Human Capital (peer discussion)', 'N/A',
    'Co-investing workshop with ADAP (peer discussion)', 'N/A',
    'Fundraising 3.0 – local capital (peer discussion)', 'N/A',
    'Ag/food tech: Investing across emerging and mature markets (collaboration with GITA)', 'N/A',
    'Mentoring Pilot Kick-off', 'N/A'
  ),
  'open discussion with peers were very interesting and insightful',
  'WhatsApp only',
  jsonb_build_object(
    'Peer connections and peer learning', 1,
    'Advocacy for early stage investing ', 1,
    'Raised profile/visibility (individual or collective)', 1,
    'Systems change to drive more capital towards local capital providers', 1
  ),
  false,
  jsonb_build_object(
    'Warehousing/seed funding for fund managers to build track record', 1,
    'TA facility to support early fund economics and activities', 1,
    'Advocacy for the early-stage investing ecosystem', 1,
    'Mentoring program (expert led)', 3,
    'Mentoring program (peer-led)', 3,
    'Webinars with peer-to-peer feedback sessions', 1,
    'Webinars with expert-led feedback sessions', 1,
    'Fundraising Readiness Advisory Program for fund managers', 1,
    'Investment readiness for portfolio companies', 3,
    'Fund Manager Portal (ie library of resources, templates etc)', 3,
    'Shared financial and impact performance data (eg a "Bloomberg" for early stage funds)', 3,
    'Joint back office between actively investing fund managers', 3
  ),
  'Yes, as a mentee',
  ARRAY['No'],
  NULL,
  '2021-01-28 05:26:31'::timestamp,
  now(),
  now()
FROM auth.users u
WHERE u.email = 'william.prothais@uberiscapital.com';

COMMIT;
