-- Create authenticated users for survey data migration
-- Default password for all users: Survey2024!

-- Insert users into auth.users
INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    confirmation_token,
    recovery_token,
    email_change_token_new,
    email_change,
    created_at,
    updated_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    is_sso_user
)
SELECT 
    '00000000-0000-0000-0000-000000000000'::uuid,
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    email,
    crypt('Survey2024!', gen_salt('bf')),
    NOW(),
    '',
    '',
    '',
    '',
    NOW(),
    NOW(),
    '{"provider": "email", "providers": ["email"]}'::jsonb,
    jsonb_build_object('email', email),
    false,
    false
FROM (
    VALUES 
        ('peter@vestedworld.com'),('amaka@weavcapital.com'),('v.tchatchueng@fakocapital.com'),
        ('finance@habacapital.com'),('amel.saidane@betawaves.io'),('cedella.besong@cfbholding.com'),
        ('o.adepoju@pearlbridgecapital.africa'),('micheal.m@bamboocp.com'),('janice@aisikicapital.com'),
        ('josh@holocene.africa'),('toukam@persistent.energy'),('Hilina@kazanafund.com'),
        ('bfaga.negocio@am.bfa.ao'),('jim@untapped-global.com'),('sven.haefner@30ThirtyCapital.com'),
        ('annan.anthony@gmail.com'),('wilfred@villgroafrica.org'),('jacobus@growthcap.co.za'),
        ('mouattara@footprint-cap.com'),('Audrey@anza.holdings'),('sawadh@ssc.co.tz'),
        ('yvonne@saharaimpactventures.com'),('Nkhulu@torhotech.com'),('tna@kukulacapital.com'),
        ('wilfred@viktoria.co.ke'),('vkiyingi@businesspartners.co.ug'),('Invest@blackstoneafrica.com'),
        ('J.namoma@nithio.com'),('egla@msftventures.com'),('sam@mirepaadvisors.com'),
        ('s.ndonga@samawaticapital.com'),('tadlam@agrifrontier.com'),('Ssircar@graymatterscap.com'),
        ('rtugume@practitionerscp.com'),('eddie.sembatya@findingxy.com'),('david.wangolo@pearlcapital.net'),
        ('p.koelbl@shequity.com'),('ashleigh.fynn-munda@opp-gen.com'),('imare@startupbugu.net'),
        ('sana@headingforchange.org'),('imandela@shonacapital.co'),('Ckirabo@mkyalaventures.com'),
        ('kim@inuacapital.com'),('agnes@firstcircle.capital'),('hema@five35.ventures'),
        ('victor.ndiege@kcv.co.ke'),('mark@bidcp.com'),('tawana@africa-growth.com'),
        ('carol.birungi@xsmlcapital.com'),('eric@happysmala.com'),('ckingombe@4ipgroup.com'),
        ('farynv@gmail.com'),('Amanda.kabagambe@tlgcapital.com'),('lidelkellytoh1989@gmail.com'),
        ('vfraser@jengacapital.com'),('nyeji@womencapital.co'),('idris@loftyinc.vc'),
        ('steven@frontend.vc'),('colin@lineacap.com'),('e.cotsoyannis@miarakap.com'),
        ('anne@sayuni.capital'),('aor@aruwacapital.com'),('andylower@adapcapital.com'),
        ('edioh@wic-capital.net'),('olivier.furdelle@terangacapital.com'),('sewu@jazarift.vc'),
        ('mamokete@mamorcapital.com'),('jaap-jan@truvalu-group.com'),('is@neper.africa'),
        ('paul@agleaseco.com'),('klegesi@ortusafrica.com'),('jesse@takeofffund.com'),
        ('jchamberlain@altreecapital.om'),('thandeka@digitalafricaventures.com'),('micheal@cosefinvest.com'),
        ('rekia@barkafund.com'),('Wakiuru@hevafund.com'),('Sejakekana@gmail.com'),
        ('jzongo@sinergiburkina.com'),('Lisa@atgsamata.com'),('roeland@iungocapital.com'),
        ('martin@warioba.ventures'),('edson@relevant.is'),('shiluba@tshiamoimpact.com'),
        ('franziska@unconventional.capital'),('patrick.mutenda@gmail.com'),('dmitry.fotiyev@brightmorecapital.com'),
        ('AndiaC@gracamacheltrust.org'),('jenny@amamventures.com'),('Lsz@nordicimpactfunds.com'),
        ('Chai@vakayi.com'),('k.owusu-sarfo@wangaracapital.com'),('ha@cra.fund'),
        ('anthony@mmfm-ltd.com'),('samuel@saviu.vc'),('teluwo@fbx.ventures'),
        ('sro@ceo-enterprises.com'),('geraldine@darenaventures.com'),('ani@mostfund.vc'),
        ('brendan@sechacapital.com'),('josh@balloonventures.com'),('wiem@actawa.com'),
        ('allert@mmfm-ltd.com'),('a.annan@impcapadv.com'),('e.ravohitrarivo@miarakap.com'),
        ('invteam@altreecapital.com'),('july.andraous@jambaar-capital.com'),('yvonne@womencapital.co'),
        ('bu@aruwacapital.com'),('a.fofana@comoecapital.com'),('ldavis@renewcapital.com'),
        ('cathy@fyrefem.com'),('nneka@vestedworld.com'),('e.arthur@wangaracapital.com'),
        ('Lmramba@gbfund.org'),('Ndeye.thiaw@brightmorecapital.com'),('tawana@afirca-growth.com'),
        ('kendi@hevafund.com'),('sejakekana@gmail.com'),('enyonam@mirepaadvisors.com'),
        ('angela@angazacapital.com'),('selma@firstcircle.capital'),('d.rono@samawaticapital.com'),
        ('tekiyor@nigeriasme.ng'),('lelemba@africatrustgroup.com'),('lthomas@samatacapital.com'),
        ('julia@lineacap.com'),('Aarthi.ramasubramanian@opesfund.eu'),('maya@womvest.club'),
        ('alyune@loftyinc.vc'),('rnyakinyua@meda.org'),('chibamba@finbond.co.zm'),
        ('d.doumbia@comoecapital.com'),('karinawong@smallfoundation.ie'),('florian.ibrahim@responsability.com'),
        ('esther@unconventional.capital'),('Kamaldine08@gmail.com'),('ndeye.thiaw@brightmorecapital.com'),
        ('audrey@anza.holdings'),('lavanya@vestedworld.com'),('M.Roestenberg@fmo.nl'),
        ('enyonam@mirepacapital.com'),('wiem.abdeljaouad@gmail.com'),('ldavis@renewstrategies.com'),
        ('innocent@anzaentrepreneurs.co.tz'),('stephengugu@viktoria.co.ke'),('h.vincent-genod@ietp.com'),
        ('mariamkamel@aucegypt.edu'),('veronique@adopes.com'),('tony@kinyungu.com'),
        ('william.prothais@uberiscapital.com'),('ali.alsuhail@kapita.iq'),('oeharmon@gemicap.com'),
        ('jason@viktoria.co.ke'),('dayo@microtraction.com'),('ambar@ibtikarfund.com'),
        ('shiva@ankurcapital.com'),('lkefela@gmail.com'),('kenza@outlierz.co'),
        ('shuyin@beaconfund.asia'),('stawia@gmail.com'),('fngenyi@sycomore-venture.com'),
        ('sam@mirepacapital.com'),('idris.bello@loftyincltd.biz'),('arthi.ramasubramanian@opesfund.eu'),
        ('sagar@firstfollowers.co'),('i.sidibe@comoecapital.com'),('victoria@gc.fund'),
        ('lkamara@sahelinvest.com'),('alberto@co.org.mx'),('karthik@sangam.vc'),
        ('klakhani@Invest2innovate.com'),('tamara@amamventures.com')
) AS emails(email)
WHERE NOT EXISTS (
    SELECT 1 FROM auth.users WHERE auth.users.email = emails.email
);

-- Create user_roles entries for all new users as 'member' role
INSERT INTO user_roles (user_id, role)
SELECT id, 'member'
FROM auth.users
WHERE email IN (
    'peter@vestedworld.com','amaka@weavcapital.com','v.tchatchueng@fakocapital.com',
    'finance@habacapital.com','amel.saidane@betawaves.io','cedella.besong@cfbholding.com',
    'o.adepoju@pearlbridgecapital.africa','micheal.m@bamboocp.com','janice@aisikicapital.com',
    'josh@holocene.africa','toukam@persistent.energy','Hilina@kazanafund.com',
    'bfaga.negocio@am.bfa.ao','jim@untapped-global.com','sven.haefner@30ThirtyCapital.com',
    'annan.anthony@gmail.com','wilfred@villgroafrica.org','jacobus@growthcap.co.za',
    'mouattara@footprint-cap.com','Audrey@anza.holdings','sawadh@ssc.co.tz',
    'yvonne@saharaimpactventures.com','Nkhulu@torhotech.com','tna@kukulacapital.com',
    'wilfred@viktoria.co.ke','vkiyingi@businesspartners.co.ug','Invest@blackstoneafrica.com',
    'J.namoma@nithio.com','egla@msftventures.com','sam@mirepaadvisors.com',
    's.ndonga@samawaticapital.com','tadlam@agrifrontier.com','Ssircar@graymatterscap.com',
    'rtugume@practitionerscp.com','eddie.sembatya@findingxy.com','david.wangolo@pearlcapital.net',
    'p.koelbl@shequity.com','ashleigh.fynn-munda@opp-gen.com','imare@startupbugu.net',
    'sana@headingforchange.org','imandela@shonacapital.co','Ckirabo@mkyalaventures.com',
    'kim@inuacapital.com','agnes@firstcircle.capital','hema@five35.ventures',
    'victor.ndiege@kcv.co.ke','mark@bidcp.com','tawana@africa-growth.com',
    'carol.birungi@xsmlcapital.com','eric@happysmala.com','ckingombe@4ipgroup.com',
    'farynv@gmail.com','Amanda.kabagambe@tlgcapital.com','lidelkellytoh1989@gmail.com',
    'vfraser@jengacapital.com','nyeji@womencapital.co','idris@loftyinc.vc',
    'steven@frontend.vc','colin@lineacap.com','e.cotsoyannis@miarakap.com',
    'anne@sayuni.capital','aor@aruwacapital.com','andylower@adapcapital.com',
    'edioh@wic-capital.net','olivier.furdelle@terangacapital.com','sewu@jazarift.vc',
    'mamokete@mamorcapital.com','jaap-jan@truvalu-group.com','is@neper.africa',
    'paul@agleaseco.com','klegesi@ortusafrica.com','jesse@takeofffund.com',
    'jchamberlain@altreecapital.om','thandeka@digitalafricaventures.com','micheal@cosefinvest.com',
    'rekia@barkafund.com','Wakiuru@hevafund.com','Sejakekana@gmail.com',
    'jzongo@sinergiburkina.com','Lisa@atgsamata.com','roeland@iungocapital.com',
    'martin@warioba.ventures','edson@relevant.is','shiluba@tshiamoimpact.com',
    'franziska@unconventional.capital','patrick.mutenda@gmail.com','dmitry.fotiyev@brightmorecapital.com',
    'AndiaC@gracamacheltrust.org','jenny@amamventures.com','Lsz@nordicimpactfunds.com',
    'Chai@vakayi.com','k.owusu-sarfo@wangaracapital.com','ha@cra.fund',
    'anthony@mmfm-ltd.com','samuel@saviu.vc','teluwo@fbx.ventures',
    'sro@ceo-enterprises.com','geraldine@darenaventures.com','ani@mostfund.vc',
    'brendan@sechacapital.com','josh@balloonventures.com','wiem@actawa.com',
    'allert@mmfm-ltd.com','a.annan@impcapadv.com','e.ravohitrarivo@miarakap.com',
    'invteam@altreecapital.com','july.andraous@jambaar-capital.com','yvonne@womencapital.co',
    'bu@aruwacapital.com','a.fofana@comoecapital.com','ldavis@renewcapital.com',
    'cathy@fyrefem.com','nneka@vestedworld.com','e.arthur@wangaracapital.com',
    'Lmramba@gbfund.org','Ndeye.thiaw@brightmorecapital.com','tawana@afirca-growth.com',
    'kendi@hevafund.com','sejakekana@gmail.com','enyonam@mirepaadvisors.com',
    'angela@angazacapital.com','selma@firstcircle.capital','d.rono@samawaticapital.com',
    'tekiyor@nigeriasme.ng','lelemba@africatrustgroup.com','lthomas@samatacapital.com',
    'julia@lineacap.com','Aarthi.ramasubramanian@opesfund.eu','maya@womvest.club',
    'alyune@loftyinc.vc','rnyakinyua@meda.org','chibamba@finbond.co.zm',
    'd.doumbia@comoecapital.com','karinawong@smallfoundation.ie','florian.ibrahim@responsability.com',
    'esther@unconventional.capital','Kamaldine08@gmail.com','ndeye.thiaw@brightmorecapital.com',
    'audrey@anza.holdings','lavanya@vestedworld.com','M.Roestenberg@fmo.nl',
    'enyonam@mirepacapital.com','wiem.abdeljaouad@gmail.com','ldavis@renewstrategies.com',
    'innocent@anzaentrepreneurs.co.tz','stephengugu@viktoria.co.ke','h.vincent-genod@ietp.com',
    'mariamkamel@aucegypt.edu','veronique@adopes.com','tony@kinyungu.com',
    'william.prothais@uberiscapital.com','ali.alsuhail@kapita.iq','oeharmon@gemicap.com',
    'jason@viktoria.co.ke','dayo@microtraction.com','ambar@ibtikarfund.com',
    'shiva@ankurcapital.com','lkefela@gmail.com','kenza@outlierz.co',
    'shuyin@beaconfund.asia','stawia@gmail.com','fngenyi@sycomore-venture.com',
    'sam@mirepacapital.com','idris.bello@loftyincltd.biz','arthi.ramasubramanian@opesfund.eu',
    'sagar@firstfollowers.co','i.sidibe@comoecapital.com','victoria@gc.fund',
    'lkamara@sahelinvest.com','alberto@co.org.mx','karthik@sangam.vc',
    'klakhani@Invest2innovate.com','tamara@amamventures.com'
)
ON CONFLICT (user_id) DO NOTHING;

-- Create user_profiles entries
INSERT INTO user_profiles (id, email, company_name, full_name, user_role)
SELECT 
    u.id,
    u.email,
    'Survey Migration',
    SPLIT_PART(u.email, '@', 1),
    'member'
FROM auth.users u
WHERE u.email IN (
    'peter@vestedworld.com','amaka@weavcapital.com','v.tchatchueng@fakocapital.com',
    'finance@habacapital.com','amel.saidane@betawaves.io','cedella.besong@cfbholding.com',
    'o.adepoju@pearlbridgecapital.africa','micheal.m@bamboocp.com','janice@aisikicapital.com',
    'josh@holocene.africa','toukam@persistent.energy','Hilina@kazanafund.com',
    'bfaga.negocio@am.bfa.ao','jim@untapped-global.com','sven.haefner@30ThirtyCapital.com',
    'annan.anthony@gmail.com','wilfred@villgroafrica.org','jacobus@growthcap.co.za',
    'mouattara@footprint-cap.com','Audrey@anza.holdings','sawadh@ssc.co.tz',
    'yvonne@saharaimpactventures.com','Nkhulu@torhotech.com','tna@kukulacapital.com',
    'wilfred@viktoria.co.ke','vkiyingi@businesspartners.co.ug','Invest@blackstoneafrica.com',
    'J.namoma@nithio.com','egla@msftventures.com','sam@mirepaadvisors.com',
    's.ndonga@samawaticapital.com','tadlam@agrifrontier.com','Ssircar@graymatterscap.com',
    'rtugume@practitionerscp.com','eddie.sembatya@findingxy.com','david.wangolo@pearlcapital.net',
    'p.koelbl@shequity.com','ashleigh.fynn-munda@opp-gen.com','imare@startupbugu.net',
    'sana@headingforchange.org','imandela@shonacapital.co','Ckirabo@mkyalaventures.com',
    'kim@inuacapital.com','agnes@firstcircle.capital','hema@five35.ventures',
    'victor.ndiege@kcv.co.ke','mark@bidcp.com','tawana@africa-growth.com',
    'carol.birungi@xsmlcapital.com','eric@happysmala.com','ckingombe@4ipgroup.com',
    'farynv@gmail.com','Amanda.kabagambe@tlgcapital.com','lidelkellytoh1989@gmail.com',
    'vfraser@jengacapital.com','nyeji@womencapital.co','idris@loftyinc.vc',
    'steven@frontend.vc','colin@lineacap.com','e.cotsoyannis@miarakap.com',
    'anne@sayuni.capital','aor@aruwacapital.com','andylower@adapcapital.com',
    'edioh@wic-capital.net','olivier.furdelle@terangacapital.com','sewu@jazarift.vc',
    'mamokete@mamorcapital.com','jaap-jan@truvalu-group.com','is@neper.africa',
    'paul@agleaseco.com','klegesi@ortusafrica.com','jesse@takeofffund.com',
    'jchamberlain@altreecapital.om','thandeka@digitalafricaventures.com','micheal@cosefinvest.com',
    'rekia@barkafund.com','Wakiuru@hevafund.com','Sejakekana@gmail.com',
    'jzongo@sinergiburkina.com','Lisa@atgsamata.com','roeland@iungocapital.com',
    'martin@warioba.ventures','edson@relevant.is','shiluba@tshiamoimpact.com',
    'franziska@unconventional.capital','patrick.mutenda@gmail.com','dmitry.fotiyev@brightmorecapital.com',
    'AndiaC@gracamacheltrust.org','jenny@amamventures.com','Lsz@nordicimpactfunds.com',
    'Chai@vakayi.com','k.owusu-sarfo@wangaracapital.com','ha@cra.fund',
    'anthony@mmfm-ltd.com','samuel@saviu.vc','teluwo@fbx.ventures',
    'sro@ceo-enterprises.com','geraldine@darenaventures.com','ani@mostfund.vc',
    'brendan@sechacapital.com','josh@balloonventures.com','wiem@actawa.com',
    'allert@mmfm-ltd.com','a.annan@impcapadv.com','e.ravohitrarivo@miarakap.com',
    'invteam@altreecapital.com','july.andraous@jambaar-capital.com','yvonne@womencapital.co',
    'bu@aruwacapital.com','a.fofana@comoecapital.com','ldavis@renewcapital.com',
    'cathy@fyrefem.com','nneka@vestedworld.com','e.arthur@wangaracapital.com',
    'Lmramba@gbfund.org','Ndeye.thiaw@brightmorecapital.com','tawana@afirca-growth.com',
    'kendi@hevafund.com','sejakekana@gmail.com','enyonam@mirepaadvisors.com',
    'angela@angazacapital.com','selma@firstcircle.capital','d.rono@samawaticapital.com',
    'tekiyor@nigeriasme.ng','lelemba@africatrustgroup.com','lthomas@samatacapital.com',
    'julia@lineacap.com','Aarthi.ramasubramanian@opesfund.eu','maya@womvest.club',
    'alyune@loftyinc.vc','rnyakinyua@meda.org','chibamba@finbond.co.zm',
    'd.doumbia@comoecapital.com','karinawong@smallfoundation.ie','florian.ibrahim@responsability.com',
    'esther@unconventional.capital','Kamaldine08@gmail.com','ndeye.thiaw@brightmorecapital.com',
    'audrey@anza.holdings','lavanya@vestedworld.com','M.Roestenberg@fmo.nl',
    'enyonam@mirepacapital.com','wiem.abdeljaouad@gmail.com','ldavis@renewstrategies.com',
    'innocent@anzaentrepreneurs.co.tz','stephengugu@viktoria.co.ke','h.vincent-genod@ietp.com',
    'mariamkamel@aucegypt.edu','veronique@adopes.com','tony@kinyungu.com',
    'william.prothais@uberiscapital.com','ali.alsuhail@kapita.iq','oeharmon@gemicap.com',
    'jason@viktoria.co.ke','dayo@microtraction.com','ambar@ibtikarfund.com',
    'shiva@ankurcapital.com','lkefela@gmail.com','kenza@outlierz.co',
    'shuyin@beaconfund.asia','stawia@gmail.com','fngenyi@sycomore-venture.com',
    'sam@mirepacapital.com','idris.bello@loftyincltd.biz','arthi.ramasubramanian@opesfund.eu',
    'sagar@firstfollowers.co','i.sidibe@comoecapital.com','victoria@gc.fund',
    'lkamara@sahelinvest.com','alberto@co.org.mx','karthik@sangam.vc',
    'klakhani@Invest2innovate.com','tamara@amamventures.com'
)
ON CONFLICT (id) DO NOTHING;

-- Summary
SELECT 
    'Users created successfully' as status,
    COUNT(*) as total_users
FROM auth.users
WHERE email IN (
    'peter@vestedworld.com','amaka@weavcapital.com','v.tchatchueng@fakocapital.com',
    'finance@habacapital.com','amel.saidane@betawaves.io','cedella.besong@cfbholding.com',
    'o.adepoju@pearlbridgecapital.africa','micheal.m@bamboocp.com','janice@aisikicapital.com',
    'josh@holocene.africa','toukam@persistent.energy','Hilina@kazanafund.com',
    'bfaga.negocio@am.bfa.ao','jim@untapped-global.com','sven.haefner@30ThirtyCapital.com',
    'annan.anthony@gmail.com','wilfred@villgroafrica.org','jacobus@growthcap.co.za',
    'mouattara@footprint-cap.com','Audrey@anza.holdings','sawadh@ssc.co.tz',
    'yvonne@saharaimpactventures.com','Nkhulu@torhotech.com','tna@kukulacapital.com',
    'wilfred@viktoria.co.ke','vkiyingi@businesspartners.co.ug','Invest@blackstoneafrica.com',
    'J.namoma@nithio.com','egla@msftventures.com','sam@mirepaadvisors.com',
    's.ndonga@samawaticapital.com','tadlam@agrifrontier.com','Ssircar@graymatterscap.com',
    'rtugume@practitionerscp.com','eddie.sembatya@findingxy.com','david.wangolo@pearlcapital.net',
    'p.koelbl@shequity.com','ashleigh.fynn-munda@opp-gen.com','imare@startupbugu.net',
    'sana@headingforchange.org','imandela@shonacapital.co','Ckirabo@mkyalaventures.com',
    'kim@inuacapital.com','agnes@firstcircle.capital','hema@five35.ventures',
    'victor.ndiege@kcv.co.ke','mark@bidcp.com','tawana@africa-growth.com',
    'carol.birungi@xsmlcapital.com','eric@happysmala.com','ckingombe@4ipgroup.com',
    'farynv@gmail.com','Amanda.kabagambe@tlgcapital.com','lidelkellytoh1989@gmail.com',
    'vfraser@jengacapital.com','nyeji@womencapital.co','idris@loftyinc.vc',
    'steven@frontend.vc','colin@lineacap.com','e.cotsoyannis@miarakap.com',
    'anne@sayuni.capital','aor@aruwacapital.com','andylower@adapcapital.com',
    'edioh@wic-capital.net','olivier.furdelle@terangacapital.com','sewu@jazarift.vc',
    'mamokete@mamorcapital.com','jaap-jan@truvalu-group.com','is@neper.africa',
    'paul@agleaseco.com','klegesi@ortusafrica.com','jesse@takeofffund.com',
    'jchamberlain@altreecapital.om','thandeka@digitalafricaventures.com','micheal@cosefinvest.com',
    'rekia@barkafund.com','Wakiuru@hevafund.com','Sejakekana@gmail.com',
    'jzongo@sinergiburkina.com','Lisa@atgsamata.com','roeland@iungocapital.com',
    'martin@warioba.ventures','edson@relevant.is','shiluba@tshiamoimpact.com',
    'franziska@unconventional.capital','patrick.mutenda@gmail.com','dmitry.fotiyev@brightmorecapital.com',
    'AndiaC@gracamacheltrust.org','jenny@amamventures.com','Lsz@nordicimpactfunds.com',
    'Chai@vakayi.com','k.owusu-sarfo@wangaracapital.com','ha@cra.fund',
    'anthony@mmfm-ltd.com','samuel@saviu.vc','teluwo@fbx.ventures',
    'sro@ceo-enterprises.com','geraldine@darenaventures.com','ani@mostfund.vc',
    'brendan@sechacapital.com','josh@balloonventures.com','wiem@actawa.com',
    'allert@mmfm-ltd.com','a.annan@impcapadv.com','e.ravohitrarivo@miarakap.com',
    'invteam@altreecapital.com','july.andraous@jambaar-capital.com','yvonne@womencapital.co',
    'bu@aruwacapital.com','a.fofana@comoecapital.com','ldavis@renewcapital.com',
    'cathy@fyrefem.com','nneka@vestedworld.com','e.arthur@wangaracapital.com',
    'Lmramba@gbfund.org','Ndeye.thiaw@brightmorecapital.com','tawana@afirca-growth.com',
    'kendi@hevafund.com','sejakekana@gmail.com','enyonam@mirepaadvisors.com',
    'angela@angazacapital.com','selma@firstcircle.capital','d.rono@samawaticapital.com',
    'tekiyor@nigeriasme.ng','lelemba@africatrustgroup.com','lthomas@samatacapital.com',
    'julia@lineacap.com','Aarthi.ramasubramanian@opesfund.eu','maya@womvest.club',
    'alyune@loftyinc.vc','rnyakinyua@meda.org','chibamba@finbond.co.zm',
    'd.doumbia@comoecapital.com','karinawong@smallfoundation.ie','florian.ibrahim@responsability.com',
    'esther@unconventional.capital','Kamaldine08@gmail.com','ndeye.thiaw@brightmorecapital.com',
    'audrey@anza.holdings','lavanya@vestedworld.com','M.Roestenberg@fmo.nl',
    'enyonam@mirepacapital.com','wiem.abdeljaouad@gmail.com','ldavis@renewstrategies.com',
    'innocent@anzaentrepreneurs.co.tz','stephengugu@viktoria.co.ke','h.vincent-genod@ietp.com',
    'mariamkamel@aucegypt.edu','veronique@adopes.com','tony@kinyungu.com',
    'william.prothais@uberiscapital.com','ali.alsuhail@kapita.iq','oeharmon@gemicap.com',
    'jason@viktoria.co.ke','dayo@microtraction.com','ambar@ibtikarfund.com',
    'shiva@ankurcapital.com','lkefela@gmail.com','kenza@outlierz.co',
    'shuyin@beaconfund.asia','stawia@gmail.com','fngenyi@sycomore-venture.com',
    'sam@mirepacapital.com','idris.bello@loftyincltd.biz','arthi.ramasubramanian@opesfund.eu',
    'sagar@firstfollowers.co','i.sidibe@comoecapital.com','victoria@gc.fund',
    'lkamara@sahelinvest.com','alberto@co.org.mx','karthik@sangam.vc',
    'klakhani@Invest2innovate.com','tamara@amamventures.com'
);